export const words= [
  { answer: "Abby", hint: "Chicken Little" },
  { answer: "Abigail", hint: "The Aristocats" },
  { answer: "Abu", hint: "Aladdin" },
  { answer: "Adelaide", hint: "The Aristocats" },
  { answer: "Adella", hint: "The Little Mermaid" },
  { answer: "Akela", hint: "The Jungle Book" },
  { answer: "Aladdin", hint: "Aladdin" },
  { answer: "Alcmene", hint: "Hercules" },
  { answer: "Alice", hint: "Alice in Wonderland" },
  { answer: "Amelia", hint: "The Aristocats" },
  { answer: "Amos", hint: "The Fox and the Hound" },
  { answer: "Anastasia", hint: "Cinderella" },
  { answer: "Andrina", hint: "The Little Mermaid" },
  { answer: "Andy", hint: "Toy Story" },
  { answer: "Anna", hint: "Frozen" },
  { answer: "Antonio", hint: "Encanto" },
  { answer: "Apollo", hint: "Hercules" },
  { answer: "Aquata", hint: "The Little Mermaid" },
  { answer: "Ariel", hint: "The Little Mermaid" },
  { answer: "Arthur", hint: "The Sword in the Stone" },
  { answer: "Aurora", hint: "Sleeping Beauty" },
  { answer: "Babette", hint: "Beauty and the Beast" },
  { answer: "Bagheera", hint: "The Jungle Book" },
  { answer: "Bailey", hint: "Finding Nemo" },
  { answer: "Baloo", hint: "The Jungle Book" },
  { answer: "Bambi", hint: "Bambi" },
  { answer: "Banzai", hint: "The Lion King" },
  { answer: "Bashful", hint: "Snow White and the Seven Dwarfs" },
  { answer: "Beast", hint: "Beauty and the Beast" },
  { answer: "Beatrice", hint: "Cinderella" },
  { answer: "Beaver", hint: "Lady and the Tramp" },
  { answer: "Belle", hint: "Beauty and the Beast" },
  { answer: "Ben", hint: "Descendants" },
  { answer: "Berlioz", hint: "The Aristocats" },
  { answer: "Bert", hint: "Mary Poppins" },
  { answer: "Bolt", hint: "Bolt" },
  { answer: "Bruce", hint: "Finding Nemo" },
  { answer: "Bruno", hint: "Encanto" },
  { answer: "Bullseye", hint: "Toy Story 2" },
  { answer: "Bruni", hint: "Frozen II" },
  { answer: "Bruno", hint: "Cinderella" },
  { answer: "Buster", hint: "Lady and the Tramp" },
  { answer: "Buzz Lightyear", hint: "Toy Story" },
  { answer: "Camilo", hint: "Encanto" },
  { answer: "Candlewick", hint: "Pinocchio" },
  { answer: "Captain Hook", hint: "Peter Pan" },
  { answer: "Chad", hint: "Descendants" },
  { answer: "Charles", hint: "Up" },
  { answer: "Charlotte", hint: "The Princess and the Frog" },
  { answer: "Chernabog", hint: "Fantasia" },
  { answer: "Chief", hint: "The Fox and the Hound" },
  { answer: "Chien", hint: "Po — Mulan" },
  { answer: "Chip", hint: "Beauty and the Beast" },
  { answer: "Christopher Robin", hint: "Winnie the Pooh" },
  { answer: "Chuck", hint: "Amphibia" },
  { answer: "Cinderella", hint: "Cinderella" },
  { answer: "Clayton", hint: "Tarzan" },
  { answer: "Cleo", hint: "Pinocchio" },
  { answer: "Coco", hint: "Coco" },
  { answer: "Cogsworth", hint: "Beauty and the Beast" },
  { answer: "Colette", hint: "Lady and the Tramp II" },
  { answer: "Cookie", hint: "Atlantis: The Lost Empire" },
  { answer: "Copper", hint: "The Fox and the Hound" },
  { answer: "Count Frollo", hint: "The Hunchback of Notre Dame" },
  { answer: "Cruella de Vil", hint: "101 Dalmatians" },
  { answer: "Daisy", hint: "Classic Disney cartoon" },
  { answer: "Darla", hint: "Finding Nemo" },
  { answer: "Destiny", hint: "Finding Nemo" },
  { answer: "Dewey", hint: "Mickey Mouse Universe" },
  { answer: "Dinah", hint: "Alice in Wonderland" },
  { answer: "Dizzy", hint: "Descendants" },
  { answer: "Doc", hint: "Snow White and the Seven Dwarfs" },
  { answer: "Dodger", hint: "Oliver & Company" },
  { answer: "Donald", hint: "Mickey Mouse Universe" },
  { answer: "Dopey", hint: "Snow White and the Seven Dwarfs" },
  { answer: "Dory", hint: "Finding Nemo" },
  { answer: "Drizella", hint: "Cinderella" },
  { answer: "Duchess", hint: "The Aristocats" },
  { answer: "Duey", hint: "DuckTales" },
  { answer: "Duke", hint: "Zootopia" },
  { answer: "Dumbo", hint: "Dumbo" },
  { answer: "Ed", hint: "The Lion King" },
  { answer: "Eeyore", hint: "Winnie the Pooh" },
  { answer: "Ellie", hint: "Up" },
  { answer: "Elliot", hint: "Pete’s Dragon" },
  { answer: "Elsa", hint: "Frozen" },
  { answer: "Enesto", hint: "Coco" },
  { answer: "Esmeralda", hint: "The Hunchback of Notre Dame" },
  { answer: "Eudora", hint: "The Princess and the Frog" },
  { answer: "Eugene", hint: "Tangled" },
  { answer: "Evie", hint: "Descendants" },
  { answer: "Evil Queen", hint: "Snow White and the Seven Dwarves" },
  { answer: "Fauna", hint: "Sleeping Beauty" },
  { answer: "Fa Zhou", hint: "Mulan" },
  { answer: "Felix", hint: "Wreck-It Ralph" },
  { answer: "Figaro", hint: "Pinocchio" },
  { answer: "Finnick", hint: "Zootopia" },
  { answer: "Flit", hint: "Pocahontas" },
  { answer: "Flora", hint: "Sleeping Beauty" },
  { answer: "Flounder", hint: "The Little Mermaid" },
  { answer: "Flower", hint: "Bambi" },
  { answer: "Flynn", hint: "Tangled" },
  { answer: "Gaston", hint: "Beauty and the Beast" },
  { answer: "Genie", hint: "Aladdin" },
  { answer: "George Banks", hint: "Mary Poppins" },
  { answer: "Geppetto", hint: "Pinocchio" },
  { answer: "Giselle", hint: "Enchanted" },
  { answer: "Goofy", hint: "Classic Disney cartoons" },
  { answer: "Grumpy", hint: "Snow White and the Seven Dwarfs" },
  { answer: "Gus", hint: "Cinderella" },
  { answer: "Hamm", hint: "Toy Story" },
  { answer: "Hans", hint: "Frozen" },
  { answer: "Happy", hint: "Snow White and the Seven Dwarfs" },
  { answer: "Hector", hint: "Coco" },
  { answer: "Hei Hei", hint: "Moana" },
  { answer: "Hercules", hint: "Hercules" },
  { answer: "Hewey", hint: "DuckTales" },
  { answer: "Hiro", hint: "Big Hero 6" },
  { answer: "Horace", hint: "101 Dalmatians" },
  { answer: "Hugo", hint: "The Hunchback of Notre Dome" },
  { answer: "Iago", hint: "Aladdin" },
  { answer: "Imelda", hint: "Coco" },
  { answer: "Isabela", hint: "Encanto" },
  { answer: "Jack", hint: "The Nightmare Before Christmas" },
  { answer: "Jafer", hint: "Aladdin" },
  { answer: "Jane", hint: "Tarzan" },
  { answer: "Jane Banks", hint: "Mary Poppins" },
  { answer: "Jaq", hint: "Cinderella" },
  { answer: "Jasmine", hint: "Aladdin" },
  { answer: "Jasper", hint: "101 Dalmatians" },
  { answer: "Jessie", hint: "Toy Story 2" },
  { answer: "Jim Hawkins", hint: "Treasure Planet" },
  { answer: "Jimmy", hint: "Pinocchio" },
  { answer: "John Smith", hint: "Pocahontas" },
  { answer: "Judy", hint: "Zootopia" },
  { answer: "Kaa", hint: "The Jungle Book" },
  { answer: "Kala", hint: "Tarzan" },
  { answer: "Kanga", hint: "Winnie the Pooh" },
  { answer: "Kessie", hint: "Winnie the Pooh" },
  { answer: "Kristoff", hint: "Frozen" },
  { answer: "Kuzco", hint: "The Emperor's New Groove" },
  { answer: "Lady", hint: "Lady and the Tramp" },
  { answer: "Lady Kluck", hint: "Robin Hood" },
  { answer: "LeFou", hint: "Beauty and the Beast" },
  { answer: "Li Shang", hint: "Mulan" },
  { answer: "Lilo", hint: "Lilo & Stitch" },
  { answer: "Ling", hint: "Mulan" },
  { answer: "Linguini", hint: "Ratatouille" },
  { answer: "Louie", hint: "DuckTales" },
  { answer: "Louis", hint: "The Princess and the Frog" },
  { answer: "Lucky", hint: "101 Dalmatians" },
  { answer: "Luisa", hint: "Encanto" },
  { answer: "Lumière", hint: "Beauty and the Beast" },
  { answer: "Mal", hint: "The Descendants" },
  { answer: "Mary Poppins", hint: "Mary Poppins" },
  { answer: "Mad Hatter", hint: "Alice in Wonderland" },
  { answer: "Marlin", hint: "Finding Nemo" },
  { answer: "Maurice", hint: "Beauty and the Beast" },
  { answer: "Maui", hint: "Moana" },
  { answer: "Max", hint: "The Little Mermaid" },
  { answer: "Meeko", hint: "Pocahontas" },
  { answer: "Megara", hint: "Hercules" },
  { answer: "Meilin Lee", hint: "Turning Red" },
  { answer: "Merida", hint: "Brave" },
  { answer: "Merryweather", hint: "Sleeping Beauty" },
  { answer: "Mickey", hint: "Classic Disney cartoons" },
  { answer: "Michael Banks", hint: "Mary Poppins" },
  { answer: "Mim", hint: "The Sword in the Stone" },
  { answer: "Minnie", hint: "Classic Disney cartoons" },
  { answer: "Moana", hint: "Moana" },
  { answer: "Mowgli", hint: "The Jungle Book" },
  { answer: "Mr. Potato Head", hint: "Toy Story" },
  { answer: "Mrs. Potts", hint: "Beauty and the Beast" },
  { answer: "Mufasa", hint: "The Lion King" },
  { answer: "Mulan", hint: "Mulan" },
  { answer: "Mushu", hint: "Mulan" },
  { answer: "Nala", hint: "The Lion King" },
  { answer: "Nana", hint: "Peter Pan" },
  { answer: "Nani", hint: "Lilo & Stitch" },
  { answer: "Nash", hint: "The Good Dinosaur" },
  { answer: "Naveen", hint: "The Princess and the Frog" },
  { answer: "Nemo", hint: "Finding Nemo" },
  { answer: "Nora", hint: "Pete's Dragon" },
  { answer: "Oliver", hint: "Oliver & Company" },
  { answer: "Oaken", hint: "Frozen" },
  { answer: "Olaf", hint: "Frozen" },
  { answer: "Pabbie", hint: "Frozen" },
  { answer: "Pacha", hint: "The Emperor's New Groove" },
  { answer: "Pascal", hint: "Tangled" },
  { answer: "Patch", hint: "101 Dalmatians" },
  { answer: "Peg", hint: "Landy and the Tramp" },
  { answer: "Pegasus", hint: "Hercules" },
  { answer: "Pepa", hint: "Encanto" },
  { answer: "Peter Pan", hint: "Peter Pan" },
  { answer: "Perdita", hint: "101 Dalmatians" },
  { answer: "Phoebus", hint: "The Hunchback of Notre Dame" },
  { answer: "Piglet", hint: "Winnie the Pooh" },
  { answer: "Pluto", hint: "Classic Disney cartoons" },
  { answer: "Pocahontas", hint: "Pocahontas" },
  { answer: "Pongo", hint: "101 Dalmatians" },
  { answer: "Prince Charming", hint: "Cinderella" },
  { answer: "Prince Edward", hint: "Enchanted" },
  { answer: "Prince Eric", hint: "The Little Mermaid" },
  { answer: "Prince Philip", hint: "Sleeping Beauty" },
  { answer: "Prudence", hint: "Cinderella" },
  { answer: "Pua", hint: "Moana" },
  { answer: "Pumbaa", hint: "The Lion King" },
  { answer: "Quasimodo", hint: "The Hunchback of Notre Dame" },
  { answer: "Queen of Hearts", hint: "Alice in Wonderland" },
  { answer: "Rafiki", hint: "The Lion King" },
  { answer: "Rajah", hint: "Aladdin" },
  { answer: "Rapunzel", hint: "Tangled" },
  { answer: "Raya", hint: "Raya and the Last Dragon" },
  { answer: "Remy", hint: "Ratatouille" },
  { answer: "Rex", hint: "Toy Story" },
  { answer: "Roger", hint: "101 Dalmatians" },
  { answer: "Rolly", hint: "101 Dalmatians" },
  { answer: "Roo", hint: "Winnie the Pooh" },
  { answer: "Russell", hint: "Up" },
  { answer: "Sally", hint: "The Nightmare Before Christmas" },
  { answer: "Sarafina", hint: "The Lion King" },
  { answer: "Scar", hint: "The Lion King" },
  { answer: "Scuttle", hint: "The Little Mermaid" },
  { answer: "Sebastian", hint: "The Little Mermaid" },
  { answer: "Sgt. Tibbs", hint: "101 Dalmatians" },
  { answer: "Shenzi", hint: "The Lion King" },
  { answer: "Shere Khan", hint: "The Jungle Book" },
  { answer: "Sid", hint: "Toy Story" },
  { answer: "Simba", hint: "The Lion King" },
  { answer: "Sleepy", hint: "Snow White and the Seven Dwarfs" },
  { answer: "Slink", hint: "Toy StorySmee — Peter Pan" },
  { answer: "Sneezy", hint: "Snow White and the Seven Dwarfs" },
  { answer: "Snow", hint: "Snow White and the Seven Dwarfs" },
  { answer: "Stella", hint: "The Princess and the Frog" },
  { answer: "Sven", hint: "Frozen" },
  { answer: "Thumper", hint: "Bambi" },
  { answer: "Tiana", hint: "The Princess and the Frog" },
  { answer: "Tigger", hint: "Winnie the Pooh" },
  { answer: "Timon", hint: "The Lion King" },
  { answer: "Timothy Q. Mouse", hint: "Dumbo" },
  { answer: "Tinker Bell", hint: "Peter Pan" },
  { answer: "Triton", hint: "The Little Mermaid" },
  { answer: "Tweedledum", hint: "Alice in Wonderland" },
  { answer: "Ursula", hint: "The Little Mermaid" },
  { answer: "Wendy", hint: "Peter Pan" },
  { answer: "White Rabbit", hint: "Alice in Wonderland" },
  { answer: "Winnie", hint: "Winnie the Pooh" },
  { answer: "Yzma", hint: "The Emperor’s New Groove" },
  { answer: "Zazu", hint: "The Lion King" },
  { answer: "Woody", hint: "Toy Story" },
  { answer: "Buzz Lightyear", hint: "Toy Story" },
  { answer: "Jessie", hint: "Toy Story" },
  { answer: "Bo Peep", hint: "Toy Story" },
  { answer: "Rex", hint: "Toy Story" },
  { answer: "Hamm", hint: "Toy Story" },
  { answer: "Mr. Potato Head", hint: "Toy Story" },
  { answer: "Mrs. Potato Head", hint: "Toy Story" },
  { answer: "Slinky Dog", hint: "Toy Story" },
  { answer: "Bullseye", hint: "Toy Story" },
  { answer: "Lotso", hint: "Toy Story 3" },
  { answer: "Zurg", hint: "Toy Story 2" },
  { answer: "Forky", hint: "Toy Story 4" },
  { answer: "Duke Caboom", hint: "Toy Story 4" },
  { answer: "Flik", hint: "A Bug's Life" },
  { answer: "Princess Atta", hint: "A Bug's Life" },
  { answer: "Dot", hint: "A Bug's Life" },
  { answer: "Hopper", hint: "A Bug's Life" },
  { answer: "Molt", hint: "A Bug's Life" },
  { answer: "Heimlich", hint: "A Bug's Life" },
  { answer: "Francis", hint: "A Bug's Life" },
  { answer: "Slim", hint: "A Bug's Life" },
  { answer: "Rosie", hint: "A Bug's Life" },
  { answer: "Dim", hint: "A Bug's Life" },
  { answer: "Sulley", hint: "Monsters, Inc." },
  { answer: "Mike Wazowski", hint: "Monsters, Inc." },
  { answer: "Boo", hint: "Monsters, Inc." },
  { answer: "Randall Boggs", hint: "Monsters, Inc." },
  { answer: "Celia Mae", hint: "Monsters, Inc." },
  { answer: "Roz", hint: "Monsters, Inc." },
  { answer: "Henry J. Waternoose", hint: "Monsters, Inc." },
  { answer: "Nemo", hint: "Finding Nemo" },
  { answer: "Marlin", hint: "Finding Nemo" },
  { answer: "Dory", hint: "Finding Nemo" },
  { answer: "Gill", hint: "Finding Nemo" },
  { answer: "Crush", hint: "Finding Nemo" },
  { answer: "Squirt", hint: "Finding Nemo" },
  { answer: "Bruce", hint: "Finding Nemo" },
  { answer: "Darla", hint: "Finding Nemo" },
  { answer: "Hank", hint: "Finding Dory" },
  { answer: "Destiny", hint: "Finding Dory" },
  { answer: "Mr. Incredible", hint: "The Incredibles" },
  { answer: "Elastigirl", hint: "The Incredibles" },
  { answer: "Violet Parr", hint: "The Incredibles" },
  { answer: "Dash Parr", hint: "The Incredibles" },
  { answer: "Jack", hint: "Jack Parr - The Incredibles" },
  { answer: "Frozone", hint: "The Incredibles" },
  { answer: "Syndrome", hint: "The Incredibles" },
  { answer: "Edna Mode", hint: "The Incredibles" },
  { answer: "Evelyn Deavor", hint: "Incredibles 2" },
  { answer: "Lightning McQueen", hint: "Cars" },
  { answer: "Mater", hint: "Cars" },
  { answer: "Sally Carrera", hint: "Cars" },
  { answer: "Doc Hudson", hint: "Cars" },
  { answer: "Luigi", hint: "Cars" },
  { answer: "Guido", hint: "Cars" },
  { answer: "Ramone", hint: "Cars" },
  { answer: "Fillmore", hint: "Cars" },
  { answer: "Chick Hicks", hint: "Cars" },
  { answer: "Cruz Ramirez", hint: "Cars 3" },
  { answer: "Jackson Storm", hint: "Cars 3" },
  { answer: "Remy", hint: "Ratatouille" },
  { answer: "Linguini", hint: "Ratatouille" },
  { answer: "Colette Tatou", hint: "Ratatouille" },
  { answer: "Anton Ego", hint: "Ratatouille" },
  { answer: "Chef Skinner", hint: "Ratatouille" },
  { answer: "Emile", hint: "Ratatouille" },
  { answer: "WALL", hint: "E - WALL-E" },
  { answer: "EVE", hint: "WALL-E" },
  { answer: "M", hint: "O - WALL-E" },
  { answer: "Auto", hint: "WALL-E" },
  { answer: "Captain McCrea", hint: "WALL-E" },
  { answer: "Carl Fredricksen", hint: "Up" },
  { answer: "Russell", hint: "Up" },
  { answer: "Dug", hint: "Up" },
  { answer: "Kevin", hint: "Up" },
  { answer: "Charles Muntz", hint: "Up" },
  { answer: "Merida", hint: "Brave" },
  { answer: "Queen Elinor", hint: "Brave" },
  { answer: "King Fergus", hint: "Brave" },
  { answer: "Harris", hint: "Brave" },
  { answer: "Hubert", hint: "Brave" },
  { answer: "Hamish", hint: "Brave" },
  { answer: "Mor'du", hint: "Brave" },
  { answer: "Joy", hint: "Inside Out" },
  { answer: "Sadness", hint: "Inside Out" },
  { answer: "Anger", hint: "Inside Out" },
  { answer: "Disgust", hint: "Inside Out" },
  { answer: "Fear", hint: "Inside Out" },
  { answer: "Riley Andersen", hint: "Inside Out" },
  { answer: "Bing Bong", hint: "Inside Out" },
  { answer: "Miguel Rivera", hint: "Coco" },
  { answer: "Hector", hint: "Coco" },
  { answer: "Ernesto de la Cruz", hint: "Coco" },
  { answer: "Mama Imelda", hint: "Coco" },
  { answer: "Dante", hint: "Coco" },
  { answer: "Abuelita", hint: "Coco" },
  { answer: "Ian Lightfoot", hint: "Onward" },
  { answer: "Barley Lightfoot", hint: "Onward" },
  { answer: "Laurel Lightfoot", hint: "Onward" },
  { answer: "Wilden Lightfoot", hint: "Onward" },
  { answer: "The Manticore", hint: "Onward" },
  { answer: "Joe Gardner", hint: "Soul" },
  { answer: "22", hint: "Soul" },
  { answer: "Moonwind", hint: "Soul" },
  { answer: "Terry", hint: "Soul" },
  { answer: "Curly", hint: "Soul" },
  { answer: "Luca Paguro", hint: "Luca" },
  { answer: "Alberto Scorfano", hint: "Luca" },
  { answer: "Giulia Marcovaldo", hint: "Luca" },
  { answer: "Ercole Visconti", hint: "Luca" },
  { answer: "Daniela Paguro", hint: "Luca" },
  { answer: "Mei Lee", hint: "Turning Red" },
  { answer: "Ming Lee", hint: "Turning Red" },
  { answer: "Miriam", hint: "Turning Red" },
  { answer: "Priya", hint: "Turning Red" },
  { answer: "Abby", hint: "Turning Red" },
  { answer: "Grandma Wu", hint: "Turning Red" },
  { answer: "Ember Lumen", hint: "Elemental" },
  { answer: "Wade Ripple", hint: "Elemental" },
  { answer: "Bernie Lumen", hint: "Elemental" },
  { answer: "Cinder Lumen", hint: "Elemental" },
  { answer: "Gale", hint: "Elemental" },
  { answer: "Andy's Room", hint: "Toy Story" },
  { answer: "Sunnyside Daycare", hint: "Toy Story 3" },
  { answer: "Bug City", hint: "A Bug's Life" },
  { answer: "Monstropolis", hint: "Monsters, Inc." },
  { answer: "Great Barrier Reef", hint: "Finding Nemo" },
  { answer: "Metroville", hint: "The Incredibles" },
  { answer: "Radiator Springs", hint: "Cars" },
  { answer: "Route 66", hint: "Cars" },
  { answer: "Gusteau's Restaurant", hint: "Ratatouille" },
  { answer: "Axiom Starliner", hint: "WALL-E" },
  { answer: "Paradise Falls", hint: "Up" },
  { answer: "DunBroch Castle", hint: "Brave" },
  { answer: "Land of the Dead", hint: "Coco" },
  { answer: "New Mushroomton", hint: "Onward" },
  { answer: "Half-Note Jazz Club", hint: "Soul" },
  { answer: "Portorosso", hint: "Luca" },
  { answer: "Element City", hint: "Elemental" },
  { answer: "Pizza Planet", hint: "Toy Story" },
  { answer: "Piston Cup", hint: "Cars" },
  { answer: "Bing Bong's Wagon Rocket", hint: "Inside Out" },
  { answer: "Ernesto's Guitar", hint: "Coco" },
  { answer: "Panda Amulet", hint: "Turning Red" },
  { answer: "Ember's Flame", hint: "Elemental" },
  { answer: "Snow White and the Seven Dwarfs", hint: "1937" },
  { answer: "Pinocchio", hint: "1940" },
  { answer: "Fantasia", hint: "1940" },
  { answer: "Dumbo", hint: "1941" },
  { answer: "Bambi", hint: "1942" },
  { answer: "Saludos Amigos", hint: "1943" },
  { answer: "The Three Caballeros", hint: "1945" },
  { answer: "Make Mine Music", hint: "1946" },
  { answer: "Fun and Fancy Free", hint: "1947" },
  { answer: "Melody Time", hint: "1948" },
  { answer: "The Adventures of Ichabod and Mr. Toad", hint: "1949" },
  { answer: "Cinderella", hint: "1950" },
  { answer: "Treasure Island", hint: "1950" },
  { answer: "Alice in Wonderland", hint: "1951" },
  { answer: "Robin Hood and His Merrie Men", hint: "1952" },
  { answer: "Peter Pan", hint: "1953" },
  { answer: "20,000 Leagues Under the Sea", hint: "1954" },
  { answer: "Lady and the Tramp", hint: "1955" },
  { answer: "Old Yeller", hint: "1957" },
  { answer: "Sleeping Beauty", hint: "1959" },
  { answer: "The Shaggy Dog", hint: "1959" },
  { answer: "Darby O'Gill and the Little People", hint: "1959" },
  { answer: "Third Man on the Mountain", hint: "1959" },
  { answer: "Kidnapped", hint: "1960" },
  { answer: "Pollyanna", hint: "1960" },
  { answer: "The Sign of Zorro", hint: "1960" },
  { answer: "Jungle Cat", hint: "1960" },
  { answer: "Ten Who Dared", hint: "1960" },
  { answer: "Swiss Family Robinson", hint: "1960" },
  { answer: "One Hundred and One Dalmatians", hint: "1961" },
  { answer: "The Absent", hint: "Minded Professor - 1961" },
  { answer: "The Parent Trap", hint: "1961" },
  { answer: "Greyfriars Bobby", hint: "1961" },
  { answer: "Babes in Toyland", hint: "1961" },
  { answer: "Moon Pilot", hint: "1962" },
  { answer: "Big Red", hint: "1962" },
  { answer: "Almost Angels", hint: "1962" },
  { answer: "The Legend of Lobo", hint: "1962" },
  { answer: "Son of Flubber", hint: "1963" },
  { answer: "Savage Sam", hint: "1963" },
  { answer: "Summer Magic", hint: "1963" },
  { answer: "The Incredible Journey", hint: "1963" },
  { answer: "The Sword in the Stone", hint: "1963" },
  { answer: "The Three Lives of Thomasina", hint: "1963" },
  { answer: "A Tiger Walks", hint: "1964" },
  { answer: "The Moon", hint: "Spinners - 1964" },
  { answer: "Mary Poppins", hint: "1964" },
  { answer: "Emil and the Detectives", hint: "1964" },
  { answer: "Those Calloways", hint: "1965" },
  { answer: "The Monkey's Uncle", hint: "1965" },
  { answer: "That Darn Cat!", hint: "1965" },
  { answer: "The Ugly Dachshund", hint: "1966" },
  { answer: "Follow Me, Boys!", hint: "1966" },
  { answer: "Monkeys, Go Home!", hint: "1967" },
  { answer: "The Happiest Millionaire", hint: "1967" },
  { answer: "The Gnome", hint: "Mobile - 1967" },
  { answer: "The Jungle Book", hint: "1967" },
  { answer: "Charlie, The Lonesome Cougar", hint: "1967" },
  { answer: "Blackbeard's Ghost", hint: "1968" },
  { answer: "Never a Dull Moment", hint: "1968" },
  { answer: "The Love Bug", hint: "1969" },
  { answer: "Smith!", hint: "1969" },
  { answer: "Rascal", hint: "1969" },
  { answer: "The Computer Wore Tennis Shoes", hint: "1969" },
  { answer: "King of the Grizzlies", hint: "1970" },
  { answer: "The Boatniks", hint: "1970" },
  { answer: "The Aristocats", hint: "1970" },
  { answer: "The Wild Country", hint: "1971" },
  { answer: "The Barefoot Executive", hint: "1971" },
  { answer: "Scandalous John", hint: "1971" },
  { answer: "Bedknobs and Broomsticks", hint: "1971" },
  { answer: "The Biscuit Eater", hint: "1972" },
  { answer: "Napoleon and Samantha", hint: "1972" },
  { answer: "Now You See Him, Now You Don't", hint: "1972" },
  { answer: "Run, Cougar, Run", hint: "1972" },
  { answer: "Snowball Express", hint: "1972" },
  { answer: "Charley and the Angel", hint: "1973" },
  { answer: "One Little Indian", hint: "1973" },
  { answer: "Robin Hood", hint: "1973" },
  { answer: "Superdad", hint: "1973" },
  { answer: "Herbie Rides Again", hint: "1974" },
  { answer: "The Bears and I", hint: "1974" },
  { answer: "The Castaway Cowboy", hint: "1974" },
  { answer: "The Island at the Top of the World", hint: "1974" },
  { answer: "The Strongest Man in the World", hint: "1975" },
  { answer: "Escape to Witch Mountain", hint: "1975" },
  { answer: "The Apple Dumpling Gang", hint: "1975" },
  { answer: "One of Our Dinosaurs is Missing", hint: "1975" },
  { answer: "Ride a Wild Pony", hint: "1976" },
  { answer: "No Deposit, No Return", hint: "1976" },
  { answer: "Gus", hint: "1976" },
  { answer: "Treasure of Matecumbe", hint: "1976" },
  { answer: "The Shaggy D.A.", hint: "1976" },
  { answer: "Freaky Friday", hint: "1977" },
  { answer: "The Littlest Horse Thieves", hint: "1977" },
  { answer: "Winnie the Pooh", hint: "1977" },
  { answer: "The Rescuers", hint: "1977" },
  { answer: "Herbie Goes to Monte Carlo", hint: "1977" },
  { answer: "Pete's Dragon", hint: "1977" },
  { answer: "Candleshoe", hint: "1978" },
  { answer: "Return from Witch Mountain", hint: "1978" },
  { answer: "The Cat from Outer Space", hint: "1978" },
  { answer: "Hot Lead and Cold Feet", hint: "1978" },
  { answer: "The Apple Dumpling Gang Rides Again", hint: "1979" },
  { answer: "Unidentified Flying Oddball", hint: "1979" },
  { answer: "The Black Hole", hint: "1979" },
  { answer: "Midnight Madness", hint: "1980" },
  { answer: "The Last Flight of Noah’s Ark", hint: "1980" },
  { answer: "Herbie Goes Bananas", hint: "1980" },
  { answer: "The Devil and Max Devlin", hint: "1981" },
  { answer: "Amy", hint: "1981" },
  { answer: "The Fox and the Hound", hint: "1981" },
  { answer: "Condorman", hint: "1981" },
  { answer: "The Watcher in the Woods", hint: "1981" },
  { answer: "Night Crossing", hint: "1982" },
  { answer: "Tron", hint: "1982" },
  { answer: "Tex", hint: "1982" },
  { answer: "Trenchcoat", hint: "1983" },
  { answer: "Something Wicked This Way Comes", hint: "1983" },
  { answer: "Never Cry Wolf", hint: "1983" },
  { answer: "Splash", hint: "1984" },
  { answer: "Tiger Town", hint: "1984" },
  { answer: "Country", hint: "1984" },
  { answer: "Return to Oz", hint: "1985" },
  { answer: "The Black Cauldron", hint: "1985" },
  { answer: "My Science Project", hint: "1985" },
  { answer: "The Journey of Natty Gann", hint: "1985" },
  { answer: "One Magic Christmas", hint: "1985" },
  { answer: "Off Beat", hint: "1986" },
  { answer: "The Great Mouse Detective", hint: "1986" },
  { answer: "Flight of the Navigator", hint: "1986" },
  { answer: "Tough Guys", hint: "1986" },
  { answer: "The Color of Money", hint: "1986" },
  { answer: "Outrageous Fortune", hint: "1987" },
  { answer: "Tin Men", hint: "1987" },
  { answer: "Ernest Goes to Camp", hint: "1987" },
  { answer: "Benji the Hunted", hint: "1987" },
  { answer: "Can't Buy Me Love", hint: "1987" },
  { answer: "Hello Again", hint: "1987" },
  { answer: "Three Men and a Baby", hint: "1987" },
  { answer: "Good Morning, Vietnam", hint: "1987" },
  { answer: "Shoot to Kill", hint: "1988" },
  { answer: "D.O.A.", hint: "1988" },
  { answer: "Return to Snowy River", hint: "1988" },
  { answer: "Big Business", hint: "1988" },
  { answer: "Who Framed Roger Rabbit", hint: "1988" },
  { answer: "Cocktail", hint: "1988" },
  { answer: "The Rescue", hint: "1988" },
  { answer: "Heartbreak Hotel", hint: "1988" },
  { answer: "The Good Mother", hint: "1988" },
  { answer: "Ernest Saves Christmas", hint: "1988" },
  { answer: "Oliver & Company", hint: "1988" },
  { answer: "Beaches", hint: "1988" },
  { answer: "Three Fugitives", hint: "1989" },
  { answer: "New York Stories", hint: "1989" },
  { answer: "Disorganized Crime", hint: "1989" },
  { answer: "Cheetah", hint: "1989" },
  { answer: "An Innocent Man", hint: "1989" },
  { answer: "Gross Anatomy", hint: "1989" },
  { answer: "The Little Mermaid", hint: "1989" },
  { answer: "Blaze", hint: "1989" },
  { answer: "Stella", hint: "1990" },
  { answer: "Where the Heart Is", hint: "1990" },
  { answer: "Ernest Goes to Jail", hint: "1990" },
  { answer: "Spaced Invaders", hint: "1990" },
  { answer: "Fire Birds", hint: "1990" },
  { answer: "Dick Tracy", hint: "1990" },
  { answer: "Betsy's Wedding", hint: "1990" },
  { answer: "Arachnophobia", hint: "1990" },
  { answer: "Ducktales", hint: "1990" },
  { answer: "Taking Care of Business", hint: "1990" },
  { answer: "Mr. Destiny", hint: "1990" },
  { answer: "The Rescuers Down Under", hint: "1990" },
  { answer: "Three Men and a Little Lady", hint: "1990" },
  { answer: "Green Card", hint: "1990" },
  { answer: "White Fang", hint: "1991" },
  { answer: "Run", hint: "1991" },
  { answer: "Scenes from a Mall", hint: "1991" },
  { answer: "Shipwrecked", hint: "1991" },
  { answer: "The Marrying Man", hint: "1991" },
  { answer: "Oscar", hint: "1991" },
  { answer: "One Good Cop", hint: "1991" },
  { answer: "What About Bob?", hint: "1991" },
  { answer: "Wild Hearts Can’t Be Broken", hint: "1991" },
  { answer: "The Rocketeer", hint: "1991" },
  { answer: "The Doctor", hint: "1991" },
  { answer: "V. I. Warshawski", hint: "1991" },
  { answer: "True Identity", hint: "1991" },
  { answer: "Paradise", hint: "1991" },
  { answer: "Deceived", hint: "1991" },
  { answer: "Ernest Scared Stupid", hint: "1991" },
  { answer: "Beauty and the Beast", hint: "1991" },
  { answer: "Medicine Man", hint: "1992" },
  { answer: "Noises Off", hint: "1992" },
  { answer: "Straight Talk", hint: "1992" },
  { answer: "Newsies", hint: "1992" },
  { answer: "Passed Away", hint: "1992" },
  { answer: "Encino Man", hint: "1992" },
  { answer: "A Stranger Among Us", hint: "1992" },
  { answer: "3 Ninjas", hint: "1992" },
  { answer: "The Gun in Betty Lou's Handbag", hint: "1992" },
  { answer: "Crossing the Bridge", hint: "1992" },
  { answer: "Sarafina!", hint: "1992" },
  { answer: "Captain Ron", hint: "1992" },
  { answer: "The Mighty Ducks", hint: "1992" },
  { answer: "Aladdin", hint: "1992" },
  { answer: "The Distinguished Gentleman", hint: "1992" },
  { answer: "The Muppet Christmas Carol", hint: "1992" },
  { answer: "The Cemetery Club", hint: "1993" },
  { answer: "Homeward Bound", hint: "The Incredible Journey - 1993" },
  { answer: "Swing Kids", hint: "1993" },
  { answer: "A Far Off Place", hint: "1993" },
  { answer: "Born Yesterday", hint: "1993" },
  { answer: "Adventures of Huck Finn", hint: "1993" },
  { answer: "Indian Summer", hint: "1993" },
  { answer: "Bound by Honor", hint: "1993" },
  { answer: "Super Mario Bros.", hint: "1993" },
  { answer: "Guilty as Sin", hint: "1993" },
  { answer: "Life with Mikey", hint: "1993" },
  { answer: "What's Love Got to Do with It", hint: "1993" },
  { answer: "Son", hint: "In-Law - 1993" },
  { answer: "My Boyfriend's Back", hint: "1993" },
  { answer: "Father Hood", hint: "1993" },
  { answer: "The Joy Luck Club", hint: "1993" },
  { answer: "Money for Nothing", hint: "1993" },
  { answer: "The Program", hint: "1993" },
  { answer: "The Nightmare Before Christmas", hint: "1993" },
  { answer: "The Three Musketeers", hint: "1993" },
  { answer: "Cabin Boy", hint: "1994" },
  { answer: "The Air Up There", hint: "1994" },
  { answer: "Iron Will", hint: "1994" },
  { answer: "My Father the Hero", hint: "1994" },
  { answer: "Blank Check", hint: "1994" },
  { answer: "Angie", hint: "1994" },
  { answer: "The Ref", hint: "1994" },
  { answer: "D2", hint: "The Mighty Ducks - 1994" },
  { answer: "Holy Matrimony", hint: "1994" },
  { answer: "White Fang 2", hint: "1994" },
  { answer: "The Inkwell", hint: "1994" },
  { answer: "The Lion King", hint: "1994" },
  { answer: "I Love Trouble", hint: "1994" },
  { answer: "Angels in the Outfield", hint: "1994" },
  { answer: "In the Army Now", hint: "1994" },
  { answer: "Color of Night", hint: "1994" },
  { answer: "It's Pat", hint: "1994" },
  { answer: "Camp Nowhere", hint: "1994" },
  { answer: "A Simple Twist of Fate", hint: "1994" },
  { answer: "Quiz Show", hint: "1994" },
  { answer: "Terminal Velocity", hint: "1994" },
  { answer: "Squanto", hint: "A Warrior's Tale - 1994" },
  { answer: "A Low Down Dirty Shame", hint: "1994" },
  { answer: "Bad Company", hint: "1995" },
  { answer: "Miami Rhapsody", hint: "1995" },
  { answer: "The Jerky Boys", hint: "1995" },
  { answer: "Heavyweights", hint: "1995" },
  { answer: "Man of the House", hint: "1995" },
  { answer: "Tall Tale", hint: "1995" },
  { answer: "Funny Bones", hint: "1995" },
  { answer: "Jefferson in Paris", hint: "1995" },
  { answer: "A Goofy Movie", hint: "1995" },
  { answer: "Crimson Tide", hint: "1995" },
  { answer: "Mad Love", hint: "1995" },
  { answer: "Pocahontas", hint: "1995" },
  { answer: "Operation Dumbo Drop", hint: "1995" },
  { answer: "A Kid in King Arthur's Court", hint: "1995" },
  { answer: "Unstrung Heroes", hint: "1995" },
  { answer: "The Big Green", hint: "1995" },
  { answer: "Dead Presidents", hint: "1995" },
  { answer: "Feast of July", hint: "1995" },
  { answer: "The Scarlet Letter", hint: "1995" },
  { answer: "Frank and Ollie", hint: "1995" },
  { answer: "Powder", hint: "1995" },
  { answer: "Toy Story", hint: "1995" },
  { answer: "Tom and Huck", hint: "1995" },
  { answer: "Mr. Holland's Opus", hint: "1996" },
  { answer: "White Squall", hint: "1996" },
  { answer: "Mr. Wrong", hint: "1996" },
  { answer: "Muppet Treasure Island", hint: "1996" },
  { answer: "Before and After", hint: "1996" },
  { answer: "Up Close and Personal", hint: "1996" },
  { answer: "Homeward Bound II", hint: "1996" },
  { answer: "Two Much", hint: "1996" },
  { answer: "Little Indian, Big City", hint: "1996" },
  { answer: "James and the Giant Peach", hint: "1996" },
  { answer: "Celtic Pride", hint: "1996" },
  { answer: "Last Dance", hint: "1996" },
  { answer: "Boys", hint: "1996" },
  { answer: "Spy Hard", hint: "1996" },
  { answer: "Eddie", hint: "1996" },
  { answer: "The Hunchback of Notre Dame", hint: "1996" },
  { answer: "Phenomenon", hint: "1996" },
  { answer: "Kazaam", hint: "1996" },
  { answer: "Jack", hint: "1996" },
  { answer: "First Kid", hint: "1966" },
  { answer: "The Rich Man's Wife", hint: "1966" },
  { answer: "D3", hint: "The Mighty Ducks - 1996" },
  { answer: "The Associate", hint: "1996" },
  { answer: "Ransom", hint: "1996" },
  { answer: "The War at Home", hint: "1996" },
  { answer: "The Preacher's Wife", hint: "1996" },
  { answer: "Metro", hint: "1997" },
  { answer: "Prefontaine", hint: "1997" },
  { answer: "Shadow Conspiracy", hint: "1997" },
  { answer: "That Darn Cat [remake]", hint: "1997" },
  { answer: "Jungle 2 Jungle", hint: "1997" },
  { answer: "The Sixth Man", hint: "1997" },
  { answer: "Gone Fishin'", hint: "1997" },
  { answer: "Hercules", hint: "1997" },
  { answer: "Nothing to Lose", hint: "1997" },
  { answer: "Air Bud", hint: "1997" },
  { answer: "A Thousand Acres", hint: "1997" },
  { answer: "Washington Square", hint: "1997" },
  { answer: "RocketMan", hint: "1997" },
  { answer: "Playing God", hint: "1997" },
  { answer: "Mr. Magoo", hint: "1997" },
  { answer: "Kundun", hint: "1998" },
  { answer: "Deep Rising", hint: "1998" },
  { answer: "Krippendorf's Tribe", hint: "1998" },
  { answer: "An Alan Smithee Film", hint: "Burn, Hollywood, Burn - 1998" },
  { answer: "Meet the Deedles", hint: "1998" },
  { answer: "Six Days, Seven Nights", hint: "1998" },
  { answer: "Mulan", hint: "1998" },
  { answer: "Firelight", hint: "1998" },
  { answer: "Simon Birch", hint: "1998" },
  { answer: "Holy Man", hint: "1998" },
  { answer: "Beloved", hint: "1998" },
  { answer: "The Waterboy", hint: "1998" },
  { answer: "I'll Be Home for Christmas", hint: "1998" },
  { answer: "A Bug's Life", hint: "1998" },
  { answer: "Mighty Joe Young", hint: "1998" },
  { answer: "A Civil Action", hint: "1999" },
  { answer: "My Favorite Martian", hint: "1999" },
  { answer: "The Other Sister", hint: "1999" },
  { answer: "Doug's 1st Movie", hint: "1999" },
  { answer: "Endurance", hint: "1999" },
  { answer: "Instinct", hint: "1999" },
  { answer: "1999", hint: "Tarzan" },
  { answer: "Summer of Sam", hint: "1999" },
  { answer: "Inspector Gadget", hint: "1999" },
  { answer: "The 13th Warrior", hint: "1999" },
  { answer: "Breakfast of Champions", hint: "1999" },
  { answer: "Mumford", hint: "1999" },
  { answer: "Mystery Alaska", hint: "1999" },
  { answer: "The Hand Behind the Mouse", hint: "The Ub Iwerks Story - 1999" },
  { answer: "The Straight Story", hint: "1999" },
  { answer: "The Insider", hint: "1999" },
  { answer: "Toy Story 2", hint: "1999" },
  { answer: "Cradle Will Rock", hint: "1999" },
  { answer: "Fantasia/2000", hint: "2000" },
  { answer: "Play It to the Bone", hint: "2000" },
  { answer: "Gun Shy", hint: "2000" },
  { answer: "The Tigger Movie", hint: "2000" },
  { answer: "Mission to Mars", hint: "2000" },
  { answer: "Whispers", hint: "2000" },
  { answer: "High Fidelity", hint: "2000" },
  { answer: "Keeping the Faith", hint: "2000" },
  { answer: "Dinosaur", hint: "2000" },
  { answer: "Shanghai Noon", hint: "2000" },
  { answer: "Disney's The Kid", hint: "2000" },
  { answer: "The Crew", hint: "2000" },
  { answer: "Duets", hint: "2000" },
  { answer: "Remember the Titans", hint: "2000" },
  { answer: "Playing Mona Lisa", hint: "2000" },
  { answer: "Unbreakable", hint: "2000" },
  { answer: "102 Dalmatians", hint: "2000" },
  { answer: "The Emperor's New Groove", hint: "2000" },
  { answer: "Double Take", hint: "2001" },
  { answer: "Recess", hint: "School's Out - 2001" },
  { answer: "Just Visiting", hint: "2001" },
  { answer: "Atlantis", hint: "The Lost Empire - 2001" },
  { answer: "crazy/beautiful", hint: "2001" },
  { answer: "The Princess Diaries", hint: "2001" },
  { answer: "Bubble Boy", hint: "2001" },
  { answer: "New Port South", hint: "2001" },
  { answer: "Max Keeble's Big Move", hint: "2001" },
  { answer: "Corky Romano", hint: "2001" },
  { answer: "Monsters, Inc.", hint: "2001" },
  { answer: "Out Cold", hint: "2001" },
  { answer: "Snow Dogs", hint: "2002" },
  { answer: "Return to Never Land", hint: "2002" },
  { answer: "Big Trouble", hint: "2002" },
  { answer: "Frank McKlusky, C.I.", hint: "2002" },
  { answer: "Bad Company", hint: "2002" },
  { answer: "Lilo & Stitch", hint: "2002" },
  { answer: "Reign of Fire", hint: "2002" },
  { answer: "The Country Bears", hint: "2002" },
  { answer: "Spirited Away", hint: "2002" },
  { answer: "Moonlight Mile", hint: "2002" },
  { answer: "Sweet Home Alabama", hint: "2002" },
  { answer: "Tuck Everlasting", hint: "2002" },
  { answer: "Treasure Planet", hint: "2002" },
  { answer: "The Hot Chick", hint: "2002" },
  { answer: "25th Hour", hint: "2002" },
  { answer: "Shanghai Knights", hint: "2003" },
  { answer: "The Jungle Book 2", hint: "2003" },
  { answer: "Bringing Down the House", hint: "2003" },
  { answer: "Piglet's Big Movie", hint: "2003" },
  { answer: "Ghosts of the Abyss", hint: "2003" },
  { answer: "Holes", hint: "2003" },
  { answer: "The Lizzie McGuire Movie", hint: "2003" },
  { answer: "Finding Nemo", hint: "2003" },
  { answer: "Pirates of the Caribbean", hint: "2003" },
  { answer: "Freaky Friday", hint: "2003" },
  { answer: "Open Range", hint: "2003" },
  { answer: "Hope Springs", hint: "2003" },
  { answer: "Cold Creek Manor", hint: "2003" },
  { answer: "Under the Tuscan Sun", hint: "2003" },
  { answer: "Veronica Guerin", hint: "2003" },
  { answer: "Brother Bear", hint: "2003" },
  { answer: "The Haunted Mansion", hint: "2003" },
  { answer: "The Young Black Stallion", hint: "2003" },
  { answer: "Teacher's Pet", hint: "2004" },
  { answer: "Miracle", hint: "2004" },
  { answer: "Confessions of a Teenage Drama Queen", hint: "2004" },
  { answer: "Hidalgo", hint: "2004" },
  { answer: "Home on the Range", hint: "2004" },
  { answer: "The Alamo", hint: "2004" },
  { answer: "Sacred Planet", hint: "2004" },
  { answer: "Raising Helen", hint: "2004" },
  { answer: "Around the World in 80 Days", hint: "2004" },
  { answer: "America's Heart & Soul", hint: "2004" },
  { answer: "King Arthur", hint: "2004" },
  { answer: "The Village", hint: "2004" },
  { answer: "The Princess Diaries 2", hint: "2004" },
  { answer: "Mr. 3000", hint: "2004" },
  { answer: "The Last Shot", hint: "2004" },
  { answer: "The Incredibles", hint: "2004" },
  { answer: "National Treasure", hint: "2004" },
  { answer: "Aliens of the Deep", hint: "2005" },
  { answer: "Pooh's Heffalump Movie", hint: "2005" },
  { answer: "The Pacifier", hint: "2005" },
  { answer: "Ice Princess", hint: "2005" },
  { answer: "A Lot Like Love", hint: "2005" },
  { answer: "The Hitchhiker's Guide to the Galaxy", hint: "2005" },
  { answer: "Howl's Moving Castle", hint: "2005" },
  { answer: "Herbie", hint: "Fully Loaded - 2005" },
  { answer: "Sky High", hint: "2005" },
  { answer: "Valiant", hint: "2005" },
  { answer: "The Greatest Game Ever Played", hint: "2005" },
  { answer: "Shopgirl", hint: "2005" },
  { answer: "Chicken Little", hint: "2005" },
  { answer: "The Chronicles of Narnia", hint: "2005" },
  { answer: "Glory Road", hint: "2006" },
  { answer: "Annapolis", hint: "2006" },
  { answer: "Roving Mars", hint: "2006" },
  { answer: "Eight Below", hint: "2006" },
  { answer: "The Shaggy Dog", hint: "2006" },
  { answer: "Stay Alive", hint: "2006" },
  { answer: "The Wild", hint: "2006" },
  { answer: "Stick It", hint: "2006" },
  { answer: "Goal! The Dream Begins", hint: "2006" },
  { answer: "Cars", hint: "2006" },
  { answer: "Step Up", hint: "2006" },
  { answer: "Invincible", hint: "2006" },
  { answer: "The Guardian", hint: "2006" },
  { answer: "Déjà Vu", hint: "2006" },
  { answer: "Apocalypto", hint: "2006" },
  { answer: "Primeval", hint: "2007" },
  { answer: "Bridge to Terabithia", hint: "2007" },
  { answer: "Wild Hogs", hint: "2007" },
  { answer: "Meet the Robinsons", hint: "2007" },
  { answer: "The Invisible", hint: "2007" },
  { answer: "Ratatouille", hint: "2007" },
  { answer: "The Secret of the Magic Gourd", hint: "2007" },
  { answer: "Underdog", hint: "2007" },
  { answer: "The Game Plan", hint: "2007" },
  { answer: "Dan in Real Life", hint: "2007" },
  { answer: "Le Premier Cri", hint: "2007" },
  { answer: "Enchanted", hint: "2007" },
  { answer: "National Treasure", hint: "Book of Secrets - 2007" },
  { answer: "College Road Trip", hint: "2008" },
  { answer: "WALL", hint: "E - 2008" },
  { answer: "Swing Vote", hint: "2008" },
  { answer: "Tinker Bell", hint: "2008" },
  { answer: "Miracle at St. Anna", hint: "2008" },
  { answer: "Beverly Hills Chihuahua", hint: "2008" },
  { answer: "Morning Light", hint: "2008" },
  { answer: "Roadside Romeo", hint: "2008" },
  { answer: "Bolt", hint: "2008" },
  { answer: "Bedtime Stories", hint: "2008" },
  { answer: "Race to Witch Mountain", hint: "2009" },
  { answer: "Hannah Montana the Movie", hint: "2009" },
  { answer: "Earth", hint: "2009" },
  { answer: "Trail of the Panda", hint: "2009" },
  { answer: "Up", hint: "2009" },
  { answer: "G", hint: "Force - 2009" },
  { answer: "Ponyo", hint: "2009" },
  { answer: "Walt & El Grupo", hint: "2009" },
  { answer: "Surrogates", hint: "2009" },
  { answer: "Tinker Bell and the Lost Treasure", hint: "2009" },
  { answer: "Kniga Masterov", hint: "2009" },
  { answer: "Disney's A Christmas Carol", hint: "2009" },
  { answer: "Old Dogs", hint: "2009" },
  { answer: "The Princess and the Frog", hint: "2009" },
  { answer: "When in Rome", hint: "2010" },
  { answer: "Alice in Wonderland", hint: "2010" },
  { answer: "Waking Sleeping Beauty", hint: "2010" },
  { answer: "The Last Song", hint: "2010" },
  { answer: "Oceans", hint: "2010" },
  { answer: "Toy Story 3", hint: "2010" },
  { answer: "The Sorcerer's Apprentice", hint: "2010" },
  { answer: "The Switch", hint: "2010" },
  { answer: "You Again", hint: "2010" },
  { answer: "Secretariat", hint: "2010" },
  { answer: "Tangled", hint: "2010" },
  { answer: "The Tempest", hint: "2010" },
  { answer: "Tron", hint: "Legacy - 2010" },
  { answer: "Gnomeo & Juliet", hint: "2011" },
  { answer: "I Am Number Four", hint: "2011" },
  { answer: "Mars Needs Moms", hint: "2011" },
  { answer: "Zokkomon", hint: "2011" },
  { answer: "Prom", hint: "2011" },
  { answer: "Cars 2", hint: "2011" },
  { answer: "Winnie the Pooh", hint: "2011" },
  { answer: "The Help", hint: "2011" },
  { answer: "Fright Night", hint: "2011" },
  { answer: "Real Steel", hint: "2011" },
  { answer: "The Muppets", hint: "2011" },
  { answer: "War Horse", hint: "2011" },
  { answer: "The Secret World of Arrietty", hint: "2012" },
  { answer: "John Carter", hint: "2012" },
  { answer: "Chimpanzee", hint: "2012" },
  { answer: "Brave", hint: "2012" },
  { answer: "Mad Buddies", hint: "2012" },
  { answer: "People Like Us", hint: "2012" },
  { answer: "The Odd Life of Timothy Green", hint: "2012" },
  { answer: "Secret of the Wings", hint: "2012" },
  { answer: "Barfi!", hint: "2012" },
  { answer: "Frankenweenie", hint: "2012" },
  { answer: "Wreck", hint: "It Ralph - 2012" },
  { answer: "Oz the Great and Powerful", hint: "2013" },
  { answer: "Wings of Life", hint: "2013" },
  { answer: "Monsters University", hint: "2013" },
  { answer: "The Lone Ranger", hint: "2013" },
  { answer: "Planes", hint: "2013" },
  { answer: "The Fifth Estate", hint: "2013" },
  { answer: "The Wind Rises", hint: "2013" },
  { answer: "Delivery Man", hint: "2013" },
  { answer: "Frozen", hint: "2013" },
  { answer: "The Pirate Fairy", hint: "2014" },
  { answer: "Muppets Most Wanted", hint: "2014" },
  { answer: "Bears", hint: "2014" },
  { answer: "Million Dollar Arm", hint: "2014" },
  { answer: "Maleficent", hint: "2014" },
  { answer: "Planes", hint: "Fire and Rescue - 2014" },
  { answer: "The Hundred", hint: "Foot Journey - 2014" },
  { answer: "Khoobsurat", hint: "2014" },
  { answer: "Big Hero 6", hint: "2014" },
  { answer: "Into The Woods", hint: "2014" },
  { answer: "Strange Magic", hint: "2015" },
  { answer: "McFarland, USA", hint: "2015" },
  { answer: "Cinderella", hint: "2015" },
  { answer: "Monkey Kingdom", hint: "2015" },
  { answer: "Tomorrowland", hint: "2015" },
  { answer: "Inside Out", hint: "2015" },
  { answer: "Schuks! Pay Back the Money!", hint: "2015" },
  { answer: "Bridge of Spies", hint: "2015" },
  { answer: "The Good Dinosaur", hint: "2015" },
  { answer: "The Finest Hours", hint: "2016" },
  { answer: "Zootopia", hint: "2016" },
  { answer: "The Jungle Book", hint: "2016" },
  { answer: "Alice Through the Looking Glass", hint: "2016" },
  { answer: "Finding Dory", hint: "2016" },
  { answer: "The BFG", hint: "2016" },
  { answer: "Pete's Dragon", hint: "2016" },
  { answer: "The Light Between Oceans", hint: "2016" },
  { answer: "Queen of Katwe", hint: "2016" },
  { answer: "Moana", hint: "2016" },
  { answer: "Dangal", hint: "2017" },
  { answer: "Beauty and the Beast", hint: "2017" },
  { answer: "Born in China", hint: "2017" },
  { answer: "Cars 3", hint: "2017" },
  { answer: "Jagga Jasoos", hint: "2017" },
  { answer: "Coco", hint: "2017" },
  { answer: "A Wrinkle in Time", hint: "2018" },
  { answer: "Incredibles 2", hint: "2018" },
  { answer: "Christopher Robin", hint: "2018" },
  { answer: "Ralph Breaks the Internet", hint: "2018" },
  { answer: "Mary Poppins Returns", hint: "2018" },
  { answer: "Dumbo", hint: "2019" },
  { answer: "Penguins", hint: "2019" },
  { answer: "Aladdin", hint: "2019" },
  { answer: "Toy Story 4", hint: "2019" },
  { answer: "The Lion King", hint: "2019" },
  { answer: "Maleficent", hint: "Mistress of Evil - 2019" },
  { answer: "Lady and the Tramp", hint: "2019" },
  { answer: "Noelle", hint: "2019" },
  { answer: "Frozen 2", hint: "2019" },
  { answer: "Togo", hint: "2019" },
  { answer: "Onward", hint: "2020" },
  { answer: "Stargirl", hint: "2020" },
  { answer: "Dolphin Reef", hint: "2020" },
  { answer: "Elephant", hint: "2020" },
  { answer: "Artemis Fowl", hint: "2020" },
  { answer: "Hamilton", hint: "2020" },
  { answer: "Magic Camp", hint: "2020" },
  { answer: "The One and Only Ivan", hint: "2020" },
  { answer: "Mulan", hint: "2020" },
  { answer: "Godmothered", hint: "2020" },
  { answer: "Safety", hint: "2020" },
  { answer: "Soul", hint: "2020" },
  { answer: "Flora & Ulysses", hint: "2021" },
  { answer: "Raya and the Last Dragon", hint: "2021" },
  { answer: "Cruella", hint: "2021" },
  { answer: "Luca", hint: "2021" },
  { answer: "Encanto", hint: "2021" },
  { answer: "Diary of a Wimpy Kid", hint: "2021" },
  { answer: "Turning Red", hint: "2022" },
  { answer: "Better Nate Than Ever", hint: "2022" },
  { answer: "Polar Bear", hint: "2022" },
  { answer: "Hollywood Stargirl", hint: "2022" },
  { answer: "Lightyear", hint: "2022" },
  { answer: "Rise", hint: "2022" },
  { answer: "Mija", hint: "2022" },
  { answer: "Strange World", hint: "2022" },
  { answer: "Disenchanted", hint: "2022" },
  { answer: "The Little Mermaid", hint: "2023" },
  { answer: "Elemental", hint: "2023" },
  { answer: "Haunted Mansion", hint: "2023" },
  { answer: "Wish", hint: "2023" },
  { answer: "Inside Out 2", hint: "2024" },
  { answer: "Blink", hint: "2024" },
  { answer: "Moana 2", hint: "2024" },
  { answer: "Mufasa", hint: "The Lion King - 2024" },
  { answer: "Snow White", hint: "2025" },
  { answer: "Lilo & Stitch", hint: "2025" },
  { answer: "Elio", hint: "2025" }
];