export const words= [
  { answer: "Abby", hint: "Chicken Little" },
  { answer: "Abigail", hint: "The Aristocats" },
  { answer: "Abu", hint: "Aladdin" },
  { answer: "Adelaide", hint: "The Aristocats" },
  { answer: "Adella", hint: "The Little Mermaid" },
  { answer: "Akela", hint: "The Jungle Book" },
  { answer: "Aladdin", hint: "Aladdin" },
  { answer: "Alcmene", hint: "Hercules" },
  { answer: "Alice", hint: "Alice in Wonderland" },
  { answer: "Amelia", hint: "The Aristocats" },
  { answer: "Amos", hint: "The Fox and the Hound" },
  { answer: "Anastasia", hint: "Cinderella" },
  { answer: "Andrina", hint: "The Little Mermaid" },
  { answer: "Andy", hint: "Toy Story" },
  { answer: "Anna", hint: "Frozen" },
  { answer: "Apollo", hint: "Hercules" },
  { answer: "Aquata", hint: "The Little Mermaid" },
  { answer: "Aurora", hint: "Sleeping Beauty" },
  { answer: "Babette", hint: "Beauty and the Beast" },
  { answer: "Bagheera", hint: "The Jungle Book" },
  { answer: "Baloo", hint: "The Jungle Book" },
  { answer: "Bambi", hint: "Bambi" },
  { answer: "Banzai", hint: "The Lion King" },
  { answer: "Bashful", hint: "Snow White and the Seven Dwarfs" },
  { answer: "Beast", hint: "Beauty and the Beast" },
  { answer: "Beatrice", hint: "Cinderella" },
  { answer: "Beaver", hint: "Lady and the Tramp" },
  { answer: "Belle", hint: "Beauty and the Beast" },
  { answer: "Ben", hint: "Descendants" },
  { answer: "Berlioz", hint: "The Aristocats" },
  { answer: "Bert", hint: "Mary Poppins" },
  { answer: "Bolt", hint: "Bolt" },
  { answer: "Bruce", hint: "Finding Nemo" },
  { answer: "Bruno", hint: "Encanto" },
  { answer: "Bullseye", hint: "Toy Story 2" },
  { answer: "Bruni", hint: "Frozen II" },
  { answer: "Bruno", hint: "Cinderella" },
  { answer: "Buster", hint: "Lady and the Tramp" },
  { answer: "Buzz Lightyear", hint: "Toy Story" },
  { answer: "Camilo", hint: "Encanto" },
  { answer: "Candlewick", hint: "Pinocchio" },
  { answer: "Captain Hook", hint: "Peter Pan" },
  { answer: "Chad", hint: "Descendants" },
  { answer: "Charles", hint: "Up" },
  { answer: "Charlotte", hint: "The Princess and the Frog" },
  { answer: "Chernabog", hint: "Fantasia" },
  { answer: "Chief", hint: "The Fox and the Hound" },
  { answer: "Chien-Po", hint: "Mulan" },
  { answer: "Chip", hint: "Beauty and the Beast" },
  { answer: "Chuck", hint: "Amphibia" },
  { answer: "Cinderella", hint: "Cinderella" },
  { answer: "Clayton", hint: "Tarzan" },
  { answer: "Cleo", hint: "Pinocchio" },
  { answer: "Coco", hint: "Coco" },
  { answer: "Cogsworth", hint: "Beauty and the Beast" },
  { answer: "Colette", hint: "Lady and the Tramp II" },
  { answer: "Cookie", hint: "Atlantis: The Lost Empire" },
  { answer: "Copper", hint: "The Fox and the Hound" },
  { answer: "Count Frollo", hint: "The Hunchback of Notre Dame" },
  { answer: "Cruella de Vil", hint: "101 Dalmatians" },
  { answer: "Daisy", hint: "Classic Disney cartoon" },
  { answer: "Darla", hint: "Finding Nemo" },
  { answer: "Destiny", hint: "Finding Nemo" },
  { answer: "Dewey", hint: "Mickey Mouse Universe" },
  { answer: "Dinah", hint: "Alice in Wonderland" },
  { answer: "Dizzy", hint: "Descendants" },
  { answer: "Doc", hint: "Snow White and the Seven Dwarfs" },
  { answer: "Dodger", hint: "Oliver & Company" },
  { answer: "Donald", hint: "Mickey Mouse Universe" },
  { answer: "Dopey", hint: "Snow White and the Seven Dwarfs" },
  { answer: "Dory", hint: "Finding Nemo" },
  { answer: "Drizella", hint: "Cinderella" },
  { answer: "Duchess", hint: "The Aristocats" },
  { answer: "Duey", hint: "DuckTales" },
  { answer: "Duke", hint: "Zootopia" },
  { answer: "Dumbo", hint: "Dumbo" },
  { answer: "Ed", hint: "The Lion King" },
  { answer: "Eeyore", hint: "Winnie the Pooh" },
  { answer: "Ellie", hint: "Up" },
  { answer: "Elliot", hint: "Pete’s Dragon" },
  { answer: "Elsa", hint: "Frozen" },
  { answer: "Enesto", hint: "Coco" },
  { answer: "Esmeralda", hint: "The Hunchback of Notre Dame" },
  { answer: "Eudora", hint: "The Princess and the Frog" },
  { answer: "Eugene", hint: "Tangled" },
  { answer: "Evie", hint: "Descendants" },
  { answer: "Evil Queen", hint: "Snow White and the Seven Dwarves" },
  { answer: "Fauna", hint: "Sleeping Beauty" },
  { answer: "Fa Zhou", hint: "Mulan" },
  { answer: "Figaro", hint: "Pinocchio" },
  { answer: "Flit", hint: "Pocahontas" },
  { answer: "Flora", hint: "Sleeping Beauty" },
  { answer: "Flounder", hint: "The Little Mermaid" },
  { answer: "Flynn", hint: "Tangled" },
  { answer: "Gaston", hint: "Beauty and the Beast" },
  { answer: "Genie", hint: "Aladdin" },
  { answer: "George Banks", hint: "Mary Poppins" },
  { answer: "Geppetto", hint: "Pinocchio" },
  { answer: "Giselle", hint: "Enchanted" },
  { answer: "Goofy", hint: "Classic Disney cartoons" },
  { answer: "Grumpy", hint: "Snow White and the Seven Dwarfs" },
  { answer: "Gus", hint: "Cinderella" },
  { answer: "Hamm", hint: "Toy Story" },
  { answer: "Hans", hint: "Frozen" },
  { answer: "Happy", hint: "Snow White and the Seven Dwarfs" },
  { answer: "Hector", hint: "Coco" },
  { answer: "Hei Hei", hint: "Moana" },
  { answer: "Hercules", hint: "Hercules" },
  { answer: "Hewey", hint: "DuckTales" },
  { answer: "Hiro", hint: "Big Hero 6" },
  { answer: "Horace", hint: "101 Dalmatians" },
  { answer: "Hugo", hint: "The Hunchback of Notre Dome" },
  { answer: "Iago", hint: "Aladdin" },
  { answer: "Imelda", hint: "Coco" },
  { answer: "Isabela", hint: "Encanto" },
  { answer: "Jack", hint: "The Nightmare Before Christmas" },
  { answer: "Jafer", hint: "Aladdin" },
  { answer: "Jane", hint: "Tarzan" },
  { answer: "Jane Banks", hint: "Mary Poppins" },
  { answer: "Jaq", hint: "Cinderella" },
  { answer: "Jasmine", hint: "Aladdin" },
  { answer: "Jasper", hint: "101 Dalmatians" },
  { answer: "Jessie", hint: "Toy Story 2" },
  { answer: "Jim Hawkins", hint: "Treasure Planet" },
  { answer: "Jimmy", hint: "Pinocchio" },
  { answer: "John Smith", hint: "Pocahontas" },
  { answer: "Judy", hint: "Zootopia" },
  { answer: "Kaa", hint: "The Jungle Book" },
  { answer: "Kala", hint: "Tarzan" },
  { answer: "Kanga", hint: "Winnie the Pooh" },
  { answer: "Kessie", hint: "Winnie the Pooh" },
  { answer: "Kristoff", hint: "Frozen" },
  { answer: "Kuzco", hint: "The Emperor’s New Groove" },
  { answer: "Lady", hint: "Lady and the Tramp" },
  { answer: "Lady Kluck", hint: "Robin Hood" },
  { answer: "LeFou", hint: "Beauty and the Beast" },
  { answer: "Li Shang", hint: "Mulan" },
  { answer: "Lilo", hint: "Lilo & Stitch" },
  { answer: "Ling", hint: "Mulan" },
  { answer: "Linguini", hint: "Ratatouille" },
  { answer: "Louie", hint: "DuckTales" },
  { answer: "Louis", hint: "The Princess and the Frog" },
  { answer: "Lucky", hint: "101 Dalmatians" },
  { answer: "Luisa", hint: "Encanto" },
  { answer: "Lumiere", hint: "Beauty and the Beast" },
  { answer: "Mal", hint: "The Descendants" },
  { answer: "Mary Poppins", hint: "Mary Poppins" },
  { answer: "Mad Hatter", hint: "Alice in Wonderland" },
  { answer: "Marlin", hint: "Finding Nemo" },
  { answer: "Maui", hint: "Moana" },
  { answer: "Max", hint: "The Little Mermaid" },
  { answer: "Meeko", hint: "Pocahontas" },
  { answer: "Meilin Lee", hint: "Turning Red" },
  { answer: "Merida", hint: "Brave" },
  { answer: "Merryweather", hint: "Sleeping Beauty" },
  { answer: "Mickey", hint: "Classic Disney cartoons" },
  { answer: "Michael Banks", hint: "Mary Poppins" },
  { answer: "Mim", hint: "The Sword in the Stone" },
  { answer: "Minnie", hint: "Classic Disney cartoons" },
  { answer: "Moana", hint: "Moana" },
  { answer: "Mowgli", hint: "The Jungle Book" },
  { answer: "Mr. Potato Head", hint: "Toy Story" },
  { answer: "Mrs. Potts", hint: "Beauty and the Beast" },
  { answer: "Mufasa", hint: "The Lion King" },
  { answer: "Mulan", hint: "Mulan" },
  { answer: "Mushu", hint: "Mulan" },
  { answer: "Nala", hint: "The Lion King" },
  { answer: "Nana", hint: "Peter Pan" },
  { answer: "Nani", hint: "Lilo & Stitch" },
  { answer: "Nash", hint: "The Good Dinosaur" },
  { answer: "Naveen", hint: "The Princess and the Frog" },
  { answer: "Nemo", hint: "Finding Nemo" },
  { answer: "Nora", hint: "Pete’s Dragon " },
  { answer: "Oliver", hint: "Oliver & Company" },
  { answer: "Oaken", hint: "Frozen" },
  { answer: "Olaf", hint: "Frozen" },
  { answer: "Pabbie", hint: "Frozen" },
  { answer: "Pacha", hint: "The Emperor’s New Groove" },
  { answer: "Pascal", hint: "Tangled" },
  { answer: "Patch", hint: "101 Dalmatians" },
  { answer: "Peg", hint: "Landy and the Tramp" },
  { answer: "Pegasus", hint: "Hercules" },
  { answer: "Pepa", hint: "Encanto" },
  { answer: "Peter Pan", hint: "Peter Pan" },
  { answer: "Perdita", hint: "101 Dalmatians" },
  { answer: "Phoebus", hint: "The Hunchback of Notre Dame" },
  { answer: "Piglet", hint: "Winnie the Pooh" },
  { answer: "Pluto", hint: "Classic Disney cartoons" },
  { answer: "Pocahontas", hint: "Pocahontas" },
  { answer: "Pongo", hint: "101 Dalmatians" },
  { answer: "Prudence", hint: "Cinderella" },
  { answer: "Pua", hint: "Moana" },
  { answer: "Pumbaa", hint: "The Lion King" },
  { answer: "Quasimodo", hint: "The Hunchback of Notre Dame" },
  { answer: "Queen of Hearts", hint: "Alice in Wonderland" },
  { answer: "Rafiki", hint: "The Lion King" },
  { answer: "Rajah", hint: "Aladdin" },
  { answer: "Rapunzel", hint: "Tangled" },
  { answer: "Raya", hint: "Raya and the Last Dragon" },
  { answer: "Remy", hint: "Ratatouille" },
  { answer: "Rex", hint: "Toy Story" },
  { answer: "Roger", hint: "101 Dalmatians" },
  { answer: "Rolly", hint: "101 Dalmatians" },
  { answer: "Roo", hint: "Winnie the Pooh" },
  { answer: "Sally", hint: "The Nightmare Before Christmas" },
  { answer: "Scar", hint: "The Lion King" },
  { answer: "Scuttle", hint: "The Little Mermaid" },
  { answer: "Sebastian", hint: "The Little Mermaid" },
  { answer: "Sgt. Tibbs", hint: "101 Dalmatians" },
  { answer: "Shenzi", hint: "The Lion King" },
  { answer: "Shere Khan", hint: "The Jungle Book" },
  { answer: "Sid", hint: "Toy Story" },
  { answer: "Simba", hint: "The Lion King" },
  { answer: "Sleepy", hint: "Snow White and the Seven Dwarfs" },
  { answer: "Slink", hint: "Toy StorySmee — Peter Pan" },
  { answer: "Sneezy", hint: "Snow White and the Seven Dwarfs" },
  { answer: "Snow", hint: "Snow White and the Seven Dwarfs" },
  { answer: "Stella", hint: "The Princess and the Frog" },
  { answer: "Sven", hint: "Frozen" },
  { answer: "Thumper", hint: "Bambi" },
  { answer: "Tiana", hint: "The Princess and the Frog" },
  { answer: "Tigger", hint: "Winnie the Pooh" },
  { answer: "Timon", hint: "The Lion King" },
  { answer: "Tinker Bell", hint: "Peter Pan" },
  { answer: "Triton", hint: "The Little Mermaid" },
  { answer: "Tweedledum", hint: "Alice in Wonderland" },
  { answer: "Ursula", hint: "The Little Mermaid" },
  { answer: "Wendy", hint: "Peter Pan" },
  { answer: "White Rabbit", hint: "Alice in Wonderland" },
  { answer: "Winnie", hint: "Winnie the Pooh" },
  { answer: "Yzma", hint: "The Emperor’s New Groove" },
  { answer: "Zazu", hint: "The Lion King" }
];