export const words = [
  // === CHARACTERS A–D ===
  { answer: "Abigail", hint: "The Aristocats" },
  { answer: "Abu", hint: "Aladdin" },
  { answer: "Adella", hint: "The Little Mermaid" },
  { answer: "Akela", hint: "The Jungle Book" },
  { answer: "Aladdin", hint: "Aladdin" },
  { answer: "Alcmene", hint: "Hercules" },
  { answer: "Alice", hint: "Alice in Wonderland" },
  { answer: "Amelia", hint: "The Aristocats" },
  { answer: "Amos Slade", hint: "The Fox and the Hound" },
  { answer: "Anastasia Tremaine", hint: "Cinderella" },
  { answer: "Andrina", hint: "The Little Mermaid" },
  { answer: "Andy", hint: "Toy Story" },
  { answer: "Anna", hint: "Frozen" },
  { answer: "Antonio", hint: "Encanto" },
  { answer: "Apollo", hint: "Hercules" },
  { answer: "Aquata", hint: "The Little Mermaid" },
  { answer: "Ariel", hint: "The Little Mermaid" },
  { answer: "Arthur", hint: "The Sword in the Stone" },
  { answer: "Aurora", hint: "Sleeping Beauty" },
  { answer: "Bagheera", hint: "The Jungle Book" },
  { answer: "Basil of Baker Street", hint: "The Great Mouse Detective" },
  { answer: "Bailey", hint: "Finding Dory" },
  { answer: "Baloo", hint: "The Jungle Book" },
  { answer: "Bambi", hint: "Bambi" },
  { answer: "Banzai", hint: "The Lion King" },
  { answer: "Bashful", hint: "Snow White and the Seven Dwarfs" },
  { answer: "Beast", hint: "Beauty and the Beast" },
  { answer: "Belle", hint: "Beauty and the Beast" },
  { answer: "Berlioz", hint: "The Aristocats" },
  { answer: "Bert", hint: "Mary Poppins" },
  { answer: "Bo Peep", hint: "Toy Story" },
  { answer: "Bolt", hint: "Bolt" },
  { answer: "Bruce", hint: "Finding Nemo" },
  { answer: "Bruno", hint: "Encanto" },
  { answer: "Bullseye", hint: "Toy Story 2" },
  { answer: "Bruni", hint: "Frozen II" },
  { answer: "Buster", hint: "Toy Story 2" },
  { answer: "Buzz Lightyear", hint: "Toy Story" },
  { answer: "Camilo", hint: "Encanto" },
  { answer: "Captain Hook", hint: "Peter Pan" },
  { answer: "Celia Mae", hint: "Monsters, Inc." },
  { answer: "Chernabog", hint: "Fantasia" },
  { answer: "Chief", hint: "The Fox and the Hound" },
  { answer: "Chip", hint: "Beauty and the Beast" },
  { answer: "Christopher Robin", hint: "Winnie the Pooh" },
  { answer: "Cinderella", hint: "Cinderella" },
  { answer: "Clayton", hint: "Tarzan" },
  { answer: "Cleo", hint: "Pinocchio" },
  { answer: "Clopin", hint: "The Hunchback of Notre Dame" },
  { answer: "Colette", hint: "Ratatouille" },
  { answer: "Copper", hint: "The Fox and the Hound" },
  { answer: "Count Frollo", hint: "The Hunchback of Notre Dame" },
  { answer: "Cruella de Vil", hint: "101 Dalmatians" },
  { answer: "Daisy Duck", hint: "Classic Disney" },
  { answer: "Darla", hint: "Finding Nemo" },
  { answer: "Dash Parr", hint: "The Incredibles" },
  { answer: "Destiny", hint: "Finding Dory" },
  { answer: "Dewey Duck", hint: "DuckTales" },
  { answer: "Dinah", hint: "Alice in Wonderland" },
  { answer: "Doc", hint: "Snow White and the Seven Dwarfs" },
  { answer: "Dodger", hint: "Oliver & Company" },
  { answer: "Donald Duck", hint: "Classic Disney" },
  { answer: "Dopey", hint: "Snow White and the Seven Dwarfs" },
  { answer: "Dory", hint: "Finding Nemo" },
  { answer: "Drizella", hint: "Cinderella" },
  { answer: "Duchess", hint: "The Aristocats" },
  { answer: "Dug", hint: "Up" },
  { answer: "Duke Weaselton", hint: "Zootopia" },
  { answer: "Dumbo", hint: "Dumbo" },
  { answer: "Dr. David Q. Dawson", hint: "The Great Mouse Detective" },

  // === PLACES A–D ===
  { answer: "Agrabah", hint: "Aladdin" },
  { answer: "Atlantica", hint: "The Little Mermaid" },
  { answer: "Arendelle", hint: "Frozen" },
  { answer: "Andy's Room", hint: "Toy Story" },
  { answer: "Bug City", hint: "A Bug's Life" },
  { answer: "DunBroch Castle", hint: "Brave" },
  { answer: "Duckburg", hint: "DuckTales" },

  // === OBJECTS A–D ===
  { answer: "Apple", hint: "Snow White (Poison Apple)" },
  { answer: "Aurora's Spinning Wheel", hint: "Sleeping Beauty" },
  { answer: "Beast's Rose", hint: "Beauty and the Beast" },
  { answer: "Buzz's Laser", hint: "Toy Story" },
  { answer: "Cinderella's Glass Slipper", hint: "Cinderella" },
  { answer: "Dumbo's Feather", hint: "Dumbo" },

  // === MOVIES A–D ===
  { answer: "Aladdin", hint: "1992" },
  { answer: "Alice in Wonderland", hint: "1951" },
  { answer: "Alice Through the Looking Glass", hint: "2016" },
  { answer: "Atlantis: The Lost Empire", hint: "2001" },
  { answer: "Bambi", hint: "1942" },
  { answer: "Bao", hint: "Pixar Short 2018" },
  { answer: "Beauty and the Beast", hint: "1991" },
  { answer: "Bedknobs and Broomsticks", hint: "1971" },
  { answer: "Big Hero 6", hint: "2014" },
  { answer: "Bolt", hint: "2008" },
  { answer: "Brave", hint: "2012" },
  { answer: "Brother Bear", hint: "2003" },
  { answer: "Burrow", hint: "Pixar Short 2020" },
  { answer: "Cars", hint: "2006" },
  { answer: "Cars 2", hint: "2011" },
  { answer: "Cars 3", hint: "2017" },
  { answer: "Cinderella", hint: "1950" },
  { answer: "Coco", hint: "2017" },
  { answer: "Cruella", hint: "2021" },
  { answer: "Day & Night", hint: "Pixar Short 2010" },
  { answer: "Dinosaur", hint: "2000" },
  { answer: "DuckTales the Movie: Treasure of the Lost Lamp", hint: "1990" },
  { answer: "Dumbo", hint: "1941" },
  
  // === CHARACTERS E–L ===
{ answer: "Ed", hint: "The Lion King" },
{ answer: "Edna Mode", hint: "The Incredibles" },
{ answer: "Eeyore", hint: "Winnie the Pooh" },
{ answer: "Elliot", hint: "Pete's Dragon" },
{ answer: "Elsa", hint: "Frozen" },
{ answer: "Emile", hint: "Ratatouille" },
{ answer: "Ernesto de la Cruz", hint: "Coco" },
{ answer: "Esmeralda", hint: "The Hunchback of Notre Dame" },
{ answer: "Eudora", hint: "The Princess and the Frog" },
{ answer: "Eugene Fitzherbert", hint: "Tangled" },
{ answer: "Evil Queen", hint: "Snow White and the Seven Dwarfs" },
{ answer: "Fa Zhou", hint: "Mulan" },
{ answer: "Faline", hint: "Bambi" },
{ answer: "Felix", hint: "Wreck-It Ralph" },
{ answer: "Figaro", hint: "Pinocchio" },
{ answer: "Finnick", hint: "Zootopia" },
{ answer: "Fidget", hint: "The Great Mouse Detective" },
{ answer: "Flit", hint: "Pocahontas" },
{ answer: "Flora", hint: "Sleeping Beauty" },
{ answer: "Flounder", hint: "The Little Mermaid" },
{ answer: "Felicia the Cat", hint: "The Great Mouse Detective" },
{ answer: "Flower", hint: "Bambi" },
{ answer: "Flynn Rider", hint: "Tangled" },
{ answer: "Forky", hint: "Toy Story 4" },
{ answer: "Francis", hint: "A Bug's Life" },
{ answer: "Frozone", hint: "The Incredibles" },
{ answer: "Gaston", hint: "Beauty and the Beast" },
{ answer: "Genie", hint: "Aladdin" },
{ answer: "Georgette", hint: "Oliver & Company" },
{ answer: "Geppetto", hint: "Pinocchio" },
{ answer: "Giselle", hint: "Enchanted" },
{ answer: "Goofy", hint: "Classic Disney" },
{ answer: "Great Mouse Detective", hint: "1986" },
{ answer: "Grumpy", hint: "Snow White and the Seven Dwarfs" },
{ answer: "Gus", hint: "Cinderella" },
{ answer: "Hades", hint: "Hercules" },
{ answer: "Hiram Flaversham", hint: "The Great Mouse Detective" },
{ answer: "Hamm", hint: "Toy Story" },
{ answer: "Hans", hint: "Frozen" },
{ answer: "Happy", hint: "Snow White and the Seven Dwarfs" },
{ answer: "Harris", hint: "Brave" },
{ answer: "Harryhausen", hint: "Monsters, Inc." },
{ answer: "Hei Hei", hint: "Moana" },
{ answer: "Hercules", hint: "Hercules" },
{ answer: "Hiro Hamada", hint: "Big Hero 6" },
{ answer: "Hopper", hint: "A Bug's Life" },
{ answer: "Horace", hint: "101 Dalmatians" },
{ answer: "Huey Duck", hint: "DuckTales" },
{ answer: "Ian Lightfoot", hint: "Onward" },
{ answer: "Imelda", hint: "Coco" },
{ answer: "Isabela", hint: "Encanto" },
{ answer: "Jack Skellington", hint: "The Nightmare Before Christmas" },
{ answer: "Jafar", hint: "Aladdin" },
{ answer: "Jane Porter", hint: "Tarzan" },
{ answer: "Jane Banks", hint: "Mary Poppins" },
{ answer: "Jaq", hint: "Cinderella" },
{ answer: "Jasmine", hint: "Aladdin" },
{ answer: "Jasper", hint: "101 Dalmatians" },
{ answer: "Jessie", hint: "Toy Story 2" },
{ answer: "Jim Hawkins", hint: "Treasure Planet" },
{ answer: "Jiminy Cricket", hint: "Pinocchio" },
{ answer: "Joe Gardner", hint: "Soul" },
{ answer: "John Smith", hint: "Pocahontas" },
{ answer: "Joy", hint: "Inside Out" },
{ answer: "Judy Hopps", hint: "Zootopia" },
{ answer: "Kaa", hint: "The Jungle Book" },
{ answer: "Kala", hint: "Tarzan" },
{ answer: "Kanga", hint: "Winnie the Pooh" },
{ answer: "Kenai", hint: "Brother Bear" },
{ answer: "Kida", hint: "Atlantis: The Lost Empire" },
{ answer: "King Candy", hint: "Wreck-It Ralph" },
{ answer: "King Fergus", hint: "Brave" },
{ answer: "King Triton", hint: "The Little Mermaid" },
{ answer: "Kristoff", hint: "Frozen" },
{ answer: "Kuzco", hint: "The Emperor's New Groove" },
{ answer: "Lady", hint: "Lady and the Tramp" },
{ answer: "Lefou", hint: "Beauty and the Beast" },
{ answer: "Li Shang", hint: "Mulan" },
{ answer: "Lightning McQueen", hint: "Cars" },
{ answer: "Lilo", hint: "Lilo & Stitch" },
{ answer: "Ling", hint: "Mulan" },
{ answer: "Linguini", hint: "Ratatouille" },
{ answer: "Louie Duck", hint: "DuckTales" },
{ answer: "Louis", hint: "The Princess and the Frog" },
{ answer: "Lotso", hint: "Toy Story 3" },
{ answer: "Luisa", hint: "Encanto" },
{ answer: "Lumiere", hint: "Beauty and the Beast" },
{ answer: "Lady Mouse", hint: "The Great Mouse Detective" },

// === PLACES E–L ===
{ answer: "Elsa's Ice Palace", hint: "Frozen" },
{ answer: "Eric's Castle", hint: "The Little Mermaid" },
{ answer: "Forest of No Return", hint: "Bedknobs and Broomsticks" },
{ answer: "Hero's Workshop", hint: "Big Hero 6" },
{ answer: "Isle of the Lost", hint: "Descendants" },
{ answer: "Jungle Cruise", hint: "Theme park / Movie" },
{ answer: "Kingdom of Corona", hint: "Tangled" },
{ answer: "Land of the Dead", hint: "Coco" },
{ answer: "London", hint: "101 Dalmatians" },

// === OBJECTS E–L ===
{ answer: "Elsa's Ice Powers", hint: "Frozen" },
{ answer: "Enchanted Rose", hint: "Beauty and the Beast" },
{ answer: "Flying Carpet", hint: "Aladdin" },
{ answer: "Genie's Lamp", hint: "Aladdin" },
{ answer: "Golden Flower", hint: "Tangled" },
{ answer: "Honey Pot", hint: "Winnie the Pooh" },
{ answer: "Invisibility Cloak", hint: "Onward" },
{ answer: "Lamp of the Gods", hint: "Hercules" },
{ answer: "Lightning Bolt", hint: "Hercules" },
{ answer: "Lumiere's Candlestick", hint: "Beauty and the Beast" },

// === MOVIES E–L ===
{ answer: "Enchanted", hint: "2007" },
{ answer: "Encanto", hint: "2021" },
{ answer: "Fantasia", hint: "1940" },
{ answer: "Fantasia 2000", hint: "1999" },
{ answer: "Finding Nemo", hint: "2003" },
{ answer: "Finding Dory", hint: "2016" },
{ answer: "Flubber", hint: "1997" },
{ answer: "Frozen", hint: "2013" },
{ answer: "Frozen II", hint: "2019" },
{ answer: "Fun and Fancy Free", hint: "1947" },
{ answer: "Goofy Movie", hint: "1995" },
{ answer: "An Extremely Goofy Movie", hint: "2000" },
{ answer: "Hercules", hint: "1997" },
{ answer: "Home on the Range", hint: "2004" },
{ answer: "Hunchback of Notre Dame", hint: "1996" },
{ answer: "Hunchback of Notre Dame II", hint: "2002" },
{ answer: "Inside Out", hint: "2015" },
{ answer: "Inside Out 2", hint: "2024" },
{ answer: "Incredibles", hint: "2004" },
{ answer: "Incredibles 2", hint: "2018" },
{ answer: "Jungle Book", hint: "1967" },
{ answer: "Jungle Book 2", hint: "2003" },
{ answer: "Lady and the Tramp", hint: "1955" },
{ answer: "Lava", hint: "Pixar Short 2014" },
{ answer: "La Luna", hint: "Pixar Short 2011" },
{ answer: "Lilo & Stitch", hint: "2002" },
{ answer: "Lilo & Stitch 2", hint: "2005" },
{ answer: "Lion King", hint: "1994" },
{ answer: "Lion King 2: Simba's Pride", hint: "1998" },
{ answer: "Lion King 1½", hint: "2004" },
{ answer: "Luca", hint: "2021" },
{ answer: "Luck of the Irish", hint: "2001" },
// === CHARACTERS M–R ===
{ answer: "Mad Hatter", hint: "Alice in Wonderland" },
{ answer: "Maleficent", hint: "Sleeping Beauty" },
{ answer: "Mal", hint: "Descendants" },
{ answer: "Marlin", hint: "Finding Nemo" },
{ answer: "Marie", hint: "The Aristocats" },
{ answer: "Marshmallow", hint: "Frozen" },
{ answer: "Mary Poppins", hint: "Mary Poppins" },
{ answer: "Maui", hint: "Moana" },
{ answer: "Maximus", hint: "Tangled" },
{ answer: "Meeko", hint: "Pocahontas" },
{ answer: "Megara", hint: "Hercules" },
{ answer: "Merida", hint: "Brave" },
{ answer: "Miss Kitty Mouse", hint: "The Great Mouse Detective" },
{ answer: "Merryweather", hint: "Sleeping Beauty" },
{ answer: "Mickey Mouse", hint: "Classic Disney" },
{ answer: "Minnie Mouse", hint: "Classic Disney" },
{ answer: "Mike Wazowski", hint: "Monsters, Inc." },
{ answer: "Miguel Rivera", hint: "Coco" },
{ answer: "Mrs. Judson", hint: "The Great Mouse Detective" },
{ answer: "Milo Thatch", hint: "Atlantis: The Lost Empire" },
{ answer: "Minnie", hint: "Classic Disney" },
{ answer: "Mowgli", hint: "The Jungle Book" },
{ answer: "Mufasa", hint: "The Lion King" },
{ answer: "Mulan", hint: "Mulan" },
{ answer: "Mushu", hint: "Mulan" },
{ answer: "Nala", hint: "The Lion King" },
{ answer: "Nani", hint: "Lilo & Stitch" },
{ answer: "Nash", hint: "The Good Dinosaur" },
{ answer: "Naveen", hint: "The Princess and the Frog" },
{ answer: "Nemo", hint: "Finding Nemo" },
{ answer: "Noccio", hint: "Pinocchio" },
{ answer: "Olivia Flaversham", hint: "The Great Mouse Detective" },
{ answer: "Olaf", hint: "Frozen" },
{ answer: "Oliver", hint: "Oliver & Company" },
{ answer: "Oaken", hint: "Frozen" },
{ answer: "Pabbie", hint: "Frozen" },
{ answer: "Pacha", hint: "The Emperor's New Groove" },
{ answer: "Pascal", hint: "Tangled" },
{ answer: "Patch", hint: "101 Dalmatians" },
{ answer: "Pegasus", hint: "Hercules" },
{ answer: "Pepa", hint: "Encanto" },
{ answer: "Perdita", hint: "101 Dalmatians" },
{ answer: "Peter Pan", hint: "Peter Pan" },
{ answer: "Phoebus", hint: "The Hunchback of Notre Dame" },
{ answer: "Piglet", hint: "Winnie the Pooh" },
{ answer: "Pinocchio", hint: "Pinocchio" },
{ answer: "Pluto", hint: "Classic Disney" },
{ answer: "Pocahontas", hint: "Pocahontas" },
{ answer: "Pongo", hint: "101 Dalmatians" },
{ answer: "Prince Charming", hint: "Cinderella" },
{ answer: "Prince Eric", hint: "The Little Mermaid" },
{ answer: "Prince Naveen", hint: "The Princess and the Frog" },
{ answer: "Prince Phillip", hint: "Sleeping Beauty" },
{ answer: "Pua", hint: "Moana" },
{ answer: "Pumbaa", hint: "The Lion King" },
{ answer: "Quasimodo", hint: "The Hunchback of Notre Dame" },
{ answer: "Queen of Hearts", hint: "Alice in Wonderland" },
{ answer: "Rabbit", hint: "Winnie the Pooh" },
{ answer: "Rafiki", hint: "The Lion King" },
{ answer: "Rajah", hint: "Aladdin" },
{ answer: "Rapunzel", hint: "Tangled" },
{ answer: "Raya", hint: "Raya and the Last Dragon" },
{ answer: "Remy", hint: "Ratatouille" },
{ answer: "Rex", hint: "Toy Story" },
{ answer: "Riley Andersen", hint: "Inside Out" },
{ answer: "Robin Hood", hint: "Robin Hood" },
{ answer: "Rolly", hint: "101 Dalmatians" },
{ answer: "Roz", hint: "Monsters, Inc." },
{ answer: "Russell", hint: "Up" },

// === PLACES M–R ===
{ answer: "Metroville", hint: "The Incredibles" },
{ answer: "Monstropolis", hint: "Monsters, Inc." },
{ answer: "Motunui", hint: "Moana" },
{ answer: "Mount Olympus", hint: "Hercules" },
{ answer: "Neverland", hint: "Peter Pan" },
{ answer: "New Mushroomton", hint: "Onward" },
{ answer: "Nomanisan Island", hint: "The Incredibles" },
{ answer: "Notre Dame Cathedral", hint: "The Hunchback of Notre Dame" },
{ answer: "Oaken's Trading Post", hint: "Frozen" },
{ answer: "Olympus Coliseum", hint: "Hercules" },
{ answer: "Paradise Falls", hint: "Up" },
{ answer: "Portorosso", hint: "Luca" },
{ answer: "Pride Rock", hint: "The Lion King" },
{ answer: "Radiator Springs", hint: "Cars" },
{ answer: "Rapunzel's Tower", hint: "Tangled" },

// === OBJECTS M–R ===
{ answer: "Magic Carpet", hint: "Aladdin" },
{ answer: "Magic Mirror", hint: "Snow White" },
{ answer: "Maui's Fishhook", hint: "Moana" },
{ answer: "Merida's Bow", hint: "Brave" },
{ answer: "Mickey's Sorcerer Hat", hint: "Fantasia" },
{ answer: "Mother Gothel's Knife", hint: "Tangled" },
{ answer: "Mr. Potato Head's Parts", hint: "Toy Story" },
{ answer: "Omnidroid", hint: "The Incredibles" },
{ answer: "Pixie Dust", hint: "Peter Pan" },
{ answer: "Poison Apple", hint: "Snow White" },
{ answer: "Rapunzel's Hair", hint: "Tangled" },
{ answer: "Remy's Spoon", hint: "Ratatouille" },
{ answer: "Rose", hint: "Beauty and the Beast" },

// === MOVIES M–R ===
{ answer: "Mary Poppins", hint: "1964" },
{ answer: "Mary Poppins Returns", hint: "2018" },
{ answer: "Meet the Robinsons", hint: "2007" },
{ answer: "Melody Time", hint: "1948" },
{ answer: "Moana", hint: "2016" },
{ answer: "Moana 2", hint: "2024" },
{ answer: "Monsters, Inc.", hint: "2001" },
{ answer: "Monsters University", hint: "2013" },
{ answer: "Mulan", hint: "1998" },
{ answer: "Mulan II", hint: "2004" },
{ answer: "Music Land", hint: "1935 short" },
{ answer: "Oliver & Company", hint: "1988" },
{ answer: "Onward", hint: "2020" },
{ answer: "Paperman", hint: "2012 short" },
{ answer: "Partly Cloudy", hint: "2009 short" },
{ answer: "Pete's Dragon", hint: "1977" },
{ answer: "Peter Pan", hint: "1953" },
{ answer: "Peter Pan & Wendy", hint: "2023" },
{ answer: "Piglet's Big Movie", hint: "2003" },
{ answer: "Pinocchio", hint: "1940" },
{ answer: "Planes", hint: "2013" },
{ answer: "Planes: Fire & Rescue", hint: "2014" },
{ answer: "Pocahontas", hint: "1995" },
{ answer: "Professor Ratigan", hint: "The Great Mouse Detective" },
{ answer: "Pocahontas II: Journey to a New World", hint: "1998" },
{ answer: "The Princess and the Frog", hint: "2009" },
{ answer: "Ralph Breaks the Internet", hint: "2018" },
{ answer: "Ratatouille", hint: "2007" },
{ answer: "Raya and the Last Dragon", hint: "2021" },
{ answer: "Rescuers", hint: "1977" },
{ answer: "Rescuers Down Under", hint: "1990" },
{ answer: "Robin Hood", hint: "1973" },
{ answer: "Runaway Brain", hint: "1995 short" },
// === CHARACTERS S–Z ===
{ answer: "Sadness", hint: "Inside Out" },
{ answer: "Sally", hint: "The Nightmare Before Christmas" },
{ answer: "Sarabi", hint: "The Lion King" },
{ answer: "Scar", hint: "The Lion King" },
{ answer: "Scrooge McDuck", hint: "DuckTales" },
{ answer: "Scuttle", hint: "The Little Mermaid" },
{ answer: "Sebastian", hint: "The Little Mermaid" },
{ answer: "Shenzi", hint: "The Lion King" },
{ answer: "Shere Khan", hint: "The Jungle Book" },
{ answer: "Sid", hint: "Toy Story" },
{ answer: "Simba", hint: "The Lion King" },
{ answer: "Slinky Dog", hint: "Toy Story" },
{ answer: "Smee", hint: "Peter Pan" },
{ answer: "Sneezy", hint: "Snow White and the Seven Dwarfs" },
{ answer: "Snow White", hint: "Snow White and the Seven Dwarfs" },
{ answer: "Stitch", hint: "Lilo & Stitch" },
{ answer: "Sulley", hint: "Monsters, Inc." },
{ answer: "Sherlock Holmes", hint: "The Great Mouse Detective" },
{ answer: "Sven", hint: "Frozen" },
{ answer: "Syndrome", hint: "The Incredibles" },
{ answer: "Toby", hint: "The Great Mouse Detective" },
{ answer: "Tarzan", hint: "Tarzan" },
{ answer: "Terk", hint: "Tarzan" },
{ answer: "Tiana", hint: "The Princess and the Frog" },
{ answer: "Tigger", hint: "Winnie the Pooh" },
{ answer: "Timon", hint: "The Lion King" },
{ answer: "Tinker Bell", hint: "Peter Pan" },
{ answer: "Tramp", hint: "Lady and the Tramp" },
{ answer: "Triton", hint: "The Little Mermaid" },
{ answer: "Tweedledum", hint: "Alice in Wonderland" },
{ answer: "Tweedledee", hint: "Alice in Wonderland" },
{ answer: "Ursula", hint: "The Little Mermaid" },
{ answer: "Vanellope von Schweetz", hint: "Wreck-It Ralph" },
{ answer: "Violet Parr", hint: "The Incredibles" },
{ answer: "WALL-E", hint: "WALL-E" },
{ answer: "Wendy Darling", hint: "Peter Pan" },
{ answer: "White Rabbit", hint: "Alice in Wonderland" },
{ answer: "Winnie the Pooh", hint: "Winnie the Pooh" },
{ answer: "Woody", hint: "Toy Story" },
{ answer: "Yzma", hint: "The Emperor's New Groove" },
{ answer: "Zazu", hint: "The Lion King" },
{ answer: "Zurg", hint: "Toy Story 2" },

// === PLACES S–Z ===
{ answer: "San Fransokyo", hint: "Big Hero 6" },
{ answer: "Scotland Highlands", hint: "Brave" },
{ answer: "Shere Khan's Jungle", hint: "The Jungle Book" },
{ answer: "Sugar Rush", hint: "Wreck-It Ralph" },
{ answer: "Sunnyside Daycare", hint: "Toy Story 3" },
{ answer: "Toontown", hint: "Who Framed Roger Rabbit" },
{ answer: "Treasure Planet", hint: "Treasure Planet" },
{ answer: "Wonderland", hint: "Alice in Wonderland" },
{ answer: "Zootopia", hint: "Zootopia" },

// === OBJECTS S–Z ===
{ answer: "Sword in the Stone", hint: "The Sword in the Stone" },
{ answer: "Tarzan's Vine", hint: "Tarzan" },
{ answer: "Tiana's Cookbook", hint: "The Princess and the Frog" },
{ answer: "Toy Story Aliens' Claw Machine", hint: "Toy Story" },
{ answer: "Trident", hint: "The Little Mermaid" },
{ answer: "Woody's Hat", hint: "Toy Story" },
{ answer: "Zootopia Carrot Pen", hint: "Zootopia" },

// === MOVIES S–Z ===
{ answer: "Saludos Amigos", hint: "1942" },
{ answer: "Sleeping Beauty", hint: "1959" },
{ answer: "Snow White and the Seven Dwarfs", hint: "1937" },
{ answer: "Soul", hint: "2020" },
{ answer: "Strange World", hint: "2022" },
{ answer: "Sword in the Stone", hint: "1963" },
{ answer: "Tangled", hint: "2010" },
{ answer: "Tarzan", hint: "1999" },
{ answer: "Tarzan II", hint: "2005" },
{ answer: "That Darn Cat!", hint: "1965" },
{ answer: "Three Caballeros", hint: "1944" },
{ answer: "Three Musketeers", hint: "2004" },
{ answer: "Tigger Movie", hint: "2000" },
{ answer: "Toy Story", hint: "1995" },
{ answer: "Toy Story 2", hint: "1999" },
{ answer: "Toy Story 3", hint: "2010" },
{ answer: "Toy Story 4", hint: "2019" },
{ answer: "Treasure Planet", hint: "2002" },
{ answer: "Turning Red", hint: "2022" },
{ answer: "Up", hint: "2009" },
{ answer: "WALL-E", hint: "2008" },
{ answer: "Wreck-It Ralph", hint: "2012" },
{ answer: "Zootopia", hint: "2016" },
{ answer: "Wish", hint: "2023" },
{ answer: "Elio", hint: "2025" },
{ answer: "Mufasa: The Lion King", hint: "2024" },

// === PIXAR SHORTS (COMPLETE) ===
{ answer: "Luxo Jr.", hint: "1986" },
{ answer: "Red's Dream", hint: "1987" },
{ answer: "Tin Toy", hint: "1988" },
{ answer: "Knick Knack", hint: "1989" },
{ answer: "Geri's Game", hint: "1997" },
{ answer: "For the Birds", hint: "2000" },
{ answer: "Mike's New Car", hint: "2002" },
{ answer: "Boundin'", hint: "2003" },
{ answer: "Jack-Jack Attack", hint: "2005" },
{ answer: "One Man Band", hint: "2005" },
{ answer: "Mater and the Ghostlight", hint: "2006" },
{ answer: "Lifted", hint: "2006" },
{ answer: "Presto", hint: "2008" },

{ answer: "Clock Cleaners", hint: "1937" },
{ answer: "The Nightmare Before Christmas", hint: "1993" },
{ answer: "Oogie Boogie", hint:"The Nightmare Before Christmas" },
{ answer: "Dr. Finkelstein", hint:"The Nightmare Before Christmas" },

{ answer: "The Blue Umbrella", hint: "2013" },

{ answer: "Sanjay's Super Team", hint: "2015" },
{ answer: "Riley's First Date?", hint: "2015" },
{ answer: "Piper", hint: "2016" },
{ answer: "Lou", hint: "2017" },

{ answer: "Kitbull", hint: "2019" },
{ answer: "Float", hint: "2019" },
{ answer: "Loop", hint: "2020" },
{ answer: "Out", hint: "2020" },

{ answer: "22 vs. Earth", hint: "2021" },
{ answer: "Ciao Alberto", hint: "2021" },
{ answer: "Dug Days", hint: "2021" },
{ answer: "Carl's Date", hint: "2023" },

// Disneyland rides
{ answer: "it's a small world", hint: "Disneyland" },
{ answer: "Pirates of the Caribbean", hint: "Disneyland" },
{ answer: "Haunted Mansion", hint: "Disneyland" },
{ answer: "Space Mountain", hint: "Disneyland" },
{ answer: "Big Thunder Mountain", hint: "Disneyland" },
{ answer: "Indiana Jones Adventure", hint: "Disneyland" },
{ answer: "Buzz Lightyear Astro Blasters", hint: "Disneyland" },
{ answer: "Radiator Springs Racers", hint: "Disneyland" },
{ answer: "Crush's Coaster", hint: "Disneyland" },
{ answer: "Soarin' Around the World", hint: "Disneyland" },
{ answer: "Ratatouille: The Adventure", hint: "Disneyland"},
{ answer: "Peter Pan's Flight", hint: "Disneyland"},
{ answer: "Tower of Terror", hint: "Disneyland"},
{ answer: "Cars Road Trip", hint: "Disneyland"},
{ answer: "RC Racer", hint: "Disneyland"},

{ answer: "Queen Mousetoria", hint: "The Great Mouse Detective" },
{ answer: "Bartholomew", hint: "The Great Mouse Detective" },
{ answer: "Stork", hint: "Clock Cleaners" }, // the sleepy stork from the short

// ==========================
// PATCH_ADD (append these)
// ==========================

// --- FILMS (WDAS/Pixar/DisneyToon/live-action remakes tied to animation) ---
{ answer: "The Many Adventures of Winnie the Pooh", hint: "1977" },
{ answer: "The Adventures of Ichabod and Mr. Toad", hint: "1949" },
{ answer: "Make Mine Music", hint: "1946" },
{ answer: "Beauty and the Beast: The Enchanted Christmas", hint: "1997" },
{ answer: "Belle's Magical World", hint: "1998" },
{ answer: "Cinderella II: Dreams Come True", hint: "2002" },
{ answer: "Cinderella III: A Twist in Time", hint: "2007" },
{ answer: "The Return of Jafar", hint: "1994" },
{ answer: "Aladdin and the King of Thieves", hint: "1996" },
{ answer: "The Little Mermaid II: Return to the Sea", hint: "2000" },
{ answer: "The Little Mermaid: Ariel's Beginning", hint: "2008" },
{ answer: "Atlantis: Milo's Return", hint: "2003" },
{ answer: "Tarzan & Jane", hint: "2002" },
{ answer: "Pooh's Grand Adventure", hint: " The Search for Christopher Robin - 1997" },
{ answer: "Winnie the Pooh: Springtime with Roo", hint: "2004" },
{ answer: "Pooh's Heffalump Movie", hint: "2005" },
{ answer: "Pooh's Heffalump Halloween Movie", hint: "2005 (video)" },
{ answer: "The Little Mermaid", hint: "2023 live-action" },
{ answer: "101 Dalmatians", hint: "1996 live-action" },
{ answer: "102 Dalmatians", hint: "2000 live-action" },

// --- PIXAR SHORTS & SPECIALS (more complete) ---
{ answer: "The Adventures of Andre & Wally B.", hint: "1984 short" },
{ answer: "Hawaiian Vacation", hint: "2011 short (Toy Story Toon)" },
{ answer: "Small Fry", hint: "2011 short (Toy Story Toon)" },
{ answer: "Partysaurus Rex", hint: "2012 short (Toy Story Toon)" },
{ answer: "Toy Story of Terror!", hint: "2013 special" },
{ answer: "Toy Story That Time Forgot", hint: "2014 special" },
{ answer: "Purl", hint: "2019 SparkShort" },
{ answer: "Smash and Grab", hint: "2019 SparkShort" },
{ answer: "Wind", hint: "2019 SparkShort" },
{ answer: "Nona", hint: "2021 SparkShort" },
{ answer: "Twenty Something", hint: "2021 SparkShort" },

// --- WDAS SHORTS (not Pixar, but Disney Animation) ---
{ answer: "Get a Horse!", hint: "2013 short" },
{ answer: "Feast", hint: "2014 short" },
{ answer: "Inner Workings", hint: "2016 short" },
{ answer: "Us Again", hint: "2021 short" },
{ answer: "Far From the Tree", hint: "2021 short" },
{ answer: "The Little Matchgirl", hint: "2006 short" },
{ answer: "Lorenzo", hint: "2004 short" },
{ answer: "The Ballad of Nessie", hint: "2011 short" },
{ answer: "Tangled Ever After", hint: "2012 short" },
{ answer: "Frozen Fever", hint: "2015 short" },
{ answer: "Olaf's Frozen Adventure", hint: "2017 special" },
{ answer: "Once Upon a Snowman", hint: "2020 short" },

// --- CHARACTERS (notable omissions) ---
{ answer: "Nick Wilde", hint: "Zootopia" },
{ answer: "Flash Slothmore", hint: "Zootopia" },
{ answer: "Mr. Big", hint: "Zootopia" },
{ answer: "Bellwether", hint: "Zootopia" },
{ answer: "Baymax", hint: "Big Hero 6" },
{ answer: "Go Go Tomago", hint: "Big Hero 6" },
{ answer: "Wasabi", hint: "Big Hero 6" },
{ answer: "Honey Lemon", hint: "Big Hero 6" },
{ answer: "Fred", hint: "Big Hero 6" },
{ answer: "Professor Callaghan", hint: "Big Hero 6" },
{ answer: "Yokai", hint: "Big Hero 6" },
{ answer: "Fix-It Felix Jr.", hint: "Wreck-It Ralph" },
{ answer: "Sergeant Calhoun", hint: "Wreck-It Ralph" },
{ answer: "Stinky Pete", hint: "Toy Story 2" },
{ answer: "Wheezy", hint: "Toy Story 2" },
{ answer: "Sarge", hint: "Toy Story" },
{ answer: "Gabby Gabby", hint: "Toy Story 4" },
{ answer: "Bing Bong", hint: "Inside Out" },
{ answer: "Dr. Facilier", hint: "The Princess and the Frog" },
{ answer: "Charlotte La Bouff", hint: "The Princess and the Frog" },
{ answer: "Mama Odie", hint: "The Princess and the Frog" },
{ answer: "Ray", hint: "The Princess and the Frog" },
{ answer: "Phil", hint: "Hercules" },
{ answer: "Pain", hint: "Hercules" },
{ answer: "Panic", hint: "Hercules" },
{ answer: "The Muses", hint: "Hercules" },
{ answer: "Kronk", hint: "The Emperor's New Groove" },
{ answer: "Commander Rourke", hint: "Atlantis: The Lost Empire" },
{ answer: "Helga Sinclair", hint: "Atlantis: The Lost Empire" },
{ answer: "Vinny Santorini", hint: "Atlantis: The Lost Empire" },
{ answer: "Dr. Sweet", hint: "Atlantis: The Lost Empire" },
{ answer: "Gaetan 'Mole' Moliere", hint: "Atlantis: The Lost Empire" },
{ answer: "John Silver", hint: "Treasure Planet" },
{ answer: "Morph", hint: "Treasure Planet" },
{ answer: "Captain Amelia", hint: "Treasure Planet" },
{ answer: "Dr. Doppler", hint: "Treasure Planet" },
{ answer: "Scroop", hint: "Treasure Planet" },
{ answer: "Arlo", hint: "The Good Dinosaur" },
{ answer: "Spot", hint: "The Good Dinosaur" },
{ answer: "Butch", hint: "The Good Dinosaur" },
{ answer: "Ramsey", hint: "The Good Dinosaur" },
{ answer: "Kerchak", hint: "Tarzan" },
{ answer: "Tantor", hint: "Tarzan" },
{ answer: "Mother Gothel", hint: "Tangled" },
{ answer: "The Witch", hint: "Brave" },
{ answer: "Will-o'-the-Wisps", hint: "Brave" },
{ answer: "Te Kā", hint: "Moana" },
{ answer: "Te Fiti", hint: "Moana" },
{ answer: "Gusteau", hint: "Ratatouille" },
{ answer: "Djali", hint: "The Hunchback of Notre Dame" },
{ answer: "Victor", hint: "The Hunchback of Notre Dame" },
{ answer: "Hugo", hint: "The Hunchback of Notre Dame" },
{ answer: "Laverne", hint: "The Hunchback of Notre Dame" },
{ answer: "Mirabel Madrigal", hint: "Encanto" },
{ answer: "Abuela Alma", hint: "Encanto" },
{ answer: "Dolores Madrigal", hint: "Encanto" },
{ answer: "Julieta Madrigal", hint: "Encanto" },
{ answer: "Mama Coco", hint: "Coco" },
{ answer: "Pepita", hint: "Coco" },
{ answer: "Colt Bronco", hint: "Onward" },
{ answer: "Boo", hint: "Monsters, Inc." },
{ answer: "Henry J. Waternoose", hint: "Monsters, Inc." },
{ answer: "George Sanderson", hint: "Monsters, Inc." },

// --- PLACES (notable omissions) ---
{ answer: "Beast's Castle", hint: "Beauty and the Beast" },
{ answer: "Gusteau's Restaurant", hint: "Ratatouille" },
{ answer: "The Axiom", hint: "WALL-E" },
{ answer: "The Great Before", hint: "Soul" },
{ answer: "The Zone", hint: "Soul" },
{ answer: "Pride Lands", hint: "The Lion King" },
{ answer: "San Fransokyo Institute of Technology", hint: "Big Hero 6" },
{ answer: "Montressor Spaceport", hint: "Treasure Planet" },
{ answer: "Scare Floor (Monsters, Inc.)", hint: "Monsters, Inc." },

// --- OBJECTS (notable omissions) ---
{ answer: "Heart of Te Fiti", hint: "Moana" },
{ answer: "Rapunzel's Frying Pan", hint: "Tangled" },
{ answer: "Super Suit", hint: "The Incredibles" },
{ answer: "Edna's No Capes Board", hint: "The Incredibles" },

{ answer: "Goofy and Wilbur", hint: "1939" },
{ answer: "Goofy's Glider", hint: "1940" },
{ answer: "Baggage Buster", hint: "1941" },
{ answer: "How to Ride a Horse", hint: "1941" },
{ answer: "The Art of Skiing", hint: "1941" },
{ answer: "The Art of Self Defense", hint: "1941" },
{ answer: "The Olympic Champ", hint: "1942" },
{ answer: "How to Fish", hint: "1942" },
{ answer: "How to Swim", hint: "1942" },
{ answer: "How to Play Golf", hint: "1944" },
{ answer: "How to Play Baseball", hint: "1942" },
{ answer: "How to Play Football", hint: "1944" },
{ answer: "Hockey Homicide", hint: "1945" },
{ answer: "Double Dribble", hint: "1946" },
{ answer: "They're Off", hint: "1948" },
{ answer: "Motor Mania", hint: "1950" }
];

